/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ClasesInterfaz.ColorBoton;
import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import ClasesSQL.LibretaClienteSQL;
import Conexion.ConexionBD;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import sun.security.util.Password;
import java.awt.Color;
import java.awt.Frame;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author jenif
 */
public class Cliente extends javax.swing.JFrame {

    Libreta libreta = new Libreta();
    String nombres = "", apellidos = "", direccion = "", telefonoMovil = "", telefonocasa = "", pass_concatenada;
    int nocliente = 0, id;
    Password contraseña3;
    boolean modoOscuro = false;
    LibretaClienteSQL libretaSQL = new LibretaClienteSQL();
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();

    /**
     * Creates new form Menu
     */
    public Cliente(String referencia) {

        //this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();

        nocliente = libretaSQL.BuscarClientePorTelefono(NombreClientetxt, ApellidoClientetxt, CelularClientetxt, TelefonoClientetxt, DireccionClientetxt, referencia);
        nocliente = libretaSQL.BuscarClientePorCelular(NombreClientetxt, ApellidoClientetxt, CelularClientetxt, TelefonoClientetxt, DireccionClientetxt, referencia);
    }

    public Cliente() {

        //  this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();

    }

    public void transparenciButton() {
        Regresarbtn.setOpaque(false);
        Regresarbtn.setContentAreaFilled(false);
        Regresarbtn.setBorderPainted(false);
        Buscarbtn.setOpaque(false);
        Buscarbtn.setContentAreaFilled(false);
        Buscarbtn.setBorderPainted(false);
        String texto = "Regresar a Menú";
        Regresarbtn.setToolTipText(texto);
        String texto2 = "Buscar Cliente por medio de una referencia";
        Buscarbtn.setToolTipText(texto2);
        String texto3 = "Guardar Cliente";
        GuardarClientebtn.setToolTipText(texto3);
        String texto4 = "Haga click para acceder a la ventana de eliminación";
        Eliminarbtn.setToolTipText(texto4);
        String texto5 = "Actualizar Cliente";
        Actualizarbtn.setToolTipText(texto5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NombreClientetxt = new javax.swing.JTextField();
        ApellidoClientetxt = new javax.swing.JTextField();
        CelularClientetxt = new javax.swing.JTextField();
        DireccionClientetxt = new javax.swing.JTextField();
        TelefonoClientetxt = new javax.swing.JTextField();
        GuardarClientebtn = new javax.swing.JButton();
        Actualizarbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Buscarbtn = new javax.swing.JButton();
        Eliminarbtn = new javax.swing.JButton();
        Regresarbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 125, 125));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(830, 460));

        NombreClientetxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreClientetxt.setForeground(new java.awt.Color(102, 102, 102));
        NombreClientetxt.setText("Nombres");
        NombreClientetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreClientetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreClientetxtActionPerformed(evt);
            }
        });
        NombreClientetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreClientetxtKeyPressed(evt);
            }
        });

        ApellidoClientetxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        ApellidoClientetxt.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoClientetxt.setText("Apellidos");
        ApellidoClientetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ApellidoClientetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoClientetxtActionPerformed(evt);
            }
        });
        ApellidoClientetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ApellidoClientetxtKeyPressed(evt);
            }
        });

        CelularClientetxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        CelularClientetxt.setForeground(new java.awt.Color(102, 102, 102));
        CelularClientetxt.setText("Celular Móvil");
        CelularClientetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CelularClientetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelularClientetxtActionPerformed(evt);
            }
        });
        CelularClientetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CelularClientetxtKeyPressed(evt);
            }
        });

        DireccionClientetxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        DireccionClientetxt.setForeground(new java.awt.Color(102, 102, 102));
        DireccionClientetxt.setText("Dirección");
        DireccionClientetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DireccionClientetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionClientetxtActionPerformed(evt);
            }
        });
        DireccionClientetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DireccionClientetxtKeyPressed(evt);
            }
        });

        TelefonoClientetxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        TelefonoClientetxt.setForeground(new java.awt.Color(102, 102, 102));
        TelefonoClientetxt.setText("Teléfono");
        TelefonoClientetxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TelefonoClientetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoClientetxtActionPerformed(evt);
            }
        });
        TelefonoClientetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelefonoClientetxtKeyPressed(evt);
            }
        });

        GuardarClientebtn.setBackground(new java.awt.Color(211, 84, 0));
        GuardarClientebtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        GuardarClientebtn.setForeground(new java.awt.Color(255, 255, 255));
        GuardarClientebtn.setText("Guardar");
        GuardarClientebtn.setBorder(null);
        GuardarClientebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GuardarClientebtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        GuardarClientebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarClientebtnActionPerformed(evt);
            }
        });

        Actualizarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Actualizarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Actualizarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Actualizarbtn.setText("Actualizar");
        Actualizarbtn.setBorder(null);
        Actualizarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Actualizarbtn.setPreferredSize(new java.awt.Dimension(144, 34));
        Actualizarbtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Actualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarbtnActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("DATOS DEL CLIENTE");

        Buscarbtn.setBackground(new java.awt.Color(102, 102, 102));
        Buscarbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Buscarbtn.setForeground(new java.awt.Color(102, 102, 102));
        Buscarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa (2).png"))); // NOI18N
        Buscarbtn.setBorder(null);
        Buscarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscarbtn.setDisabledSelectedIcon(null);
        Buscarbtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarbtnActionPerformed(evt);
            }
        });

        Eliminarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Eliminarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Eliminarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Eliminarbtn.setText("Eliminar");
        Eliminarbtn.setBorder(null);
        Eliminarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminarbtn.setMaximumSize(new java.awt.Dimension(144, 34));
        Eliminarbtn.setMinimumSize(new java.awt.Dimension(144, 34));
        Eliminarbtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarbtnActionPerformed(evt);
            }
        });

        Regresarbtn.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        Regresarbtn.setForeground(new java.awt.Color(102, 102, 102));
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        Regresarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regresarbtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(163, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DireccionClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelefonoClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CelularClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApellidoClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Actualizarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Eliminarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GuardarClientebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buscarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Regresarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GuardarClientebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(NombreClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(ApellidoClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CelularClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(TelefonoClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(DireccionClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Eliminarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Actualizarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreClientetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreClientetxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nombres = NombreClientetxt.getText();
            ApellidoClientetxt.setText("");
            ApellidoClientetxt.requestFocus();
        }
    }//GEN-LAST:event_NombreClientetxtKeyPressed

    private void NombreClientetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreClientetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreClientetxtActionPerformed

    private void ApellidoClientetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoClientetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoClientetxtActionPerformed

    private void ApellidoClientetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoClientetxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            apellidos = ApellidoClientetxt.getText();
            CelularClientetxt.setText("");
            CelularClientetxt.requestFocus();
        }
    }//GEN-LAST:event_ApellidoClientetxtKeyPressed

    private void CelularClientetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelularClientetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelularClientetxtActionPerformed

    private void CelularClientetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularClientetxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            telefonoMovil = CelularClientetxt.getText();
            TelefonoClientetxt.setText("");
            TelefonoClientetxt.requestFocus();
        }
    }//GEN-LAST:event_CelularClientetxtKeyPressed

    private void DireccionClientetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionClientetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionClientetxtActionPerformed

    private void DireccionClientetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionClientetxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            direccion = DireccionClientetxt.getText();
        }
    }//GEN-LAST:event_DireccionClientetxtKeyPressed

    private void TelefonoClientetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoClientetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoClientetxtActionPerformed

    private void TelefonoClientetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoClientetxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            telefonocasa = TelefonoClientetxt.getText();
            DireccionClientetxt.setText("");
            DireccionClientetxt.requestFocus();
        }
    }//GEN-LAST:event_TelefonoClientetxtKeyPressed

    private void GuardarClientebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClientebtnActionPerformed
        // TODO add your handling code here:
        nombres = NombreClientetxt.getText();
        apellidos = ApellidoClientetxt.getText();
        telefonoMovil = CelularClientetxt.getText();
        telefonocasa = TelefonoClientetxt.getText();
        direccion = DireccionClientetxt.getText();

        libretaSQL.InsertarLibretaCliente(nombres, apellidos, telefonoMovil, telefonocasa, direccion);
        NombreClientetxt.setText("Nombres");
        ApellidoClientetxt.setText("Apellidos");
        CelularClientetxt.setText("Celular");
        TelefonoClientetxt.setText("Teléfono");
        DireccionClientetxt.setText("Dirección");
    }//GEN-LAST:event_GuardarClientebtnActionPerformed
    private void Pintar(Color colorbotones, String imagen, Color colortexto, Color colorlabel, Color colorbase, Color colorfondo) {
        panel.setPanelBase(jPanel2);
        panel.setColorBase(colorbase);
        panel.getPanelBase();
        panel.setPanelFondo(jPanel1);
        panel.setColorFondo(colorfondo);
        panel.getPanelFondo();
        boton.setBoton(Actualizarbtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(Eliminarbtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(GuardarClientebtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();

        text.setText(NombreClientetxt);
        text.setColorTexto(colortexto);
        text.getText();
        text.setText(ApellidoClientetxt);
        text.setColorTexto(colortexto);
        text.getText();
        text.setText(CelularClientetxt);
        text.setColorTexto(colortexto);
        text.getText();
        text.setText(TelefonoClientetxt);
        text.setColorTexto(colortexto);
        text.getText();
        text.setText(DireccionClientetxt);
        text.setColorTexto(colortexto);
        text.getText();
        label.setLabel(jLabel3);
        label.setColorLabel(colorlabel);
        label.getLabel();

    }
    private void RegresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarbtnActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(1);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarbtnActionPerformed

    private void BuscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarbtnActionPerformed
        String str = JOptionPane.showInputDialog("Ingrese el ID del cliente, por favor");
        id = Integer.parseInt(str);
        libretaSQL.BuscarClientePorId(NombreClientetxt, ApellidoClientetxt, CelularClientetxt, TelefonoClientetxt, DireccionClientetxt, id);
    }//GEN-LAST:event_BuscarbtnActionPerformed

    private void EliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarbtnActionPerformed
        LibretaClientes menu = new LibretaClientes();
        menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_EliminarbtnActionPerformed

    private void ActualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarbtnActionPerformed
        // TODO add your handling code here:
        nombres = NombreClientetxt.getText();
        apellidos = ApellidoClientetxt.getText();
        telefonoMovil = CelularClientetxt.getText();
        telefonocasa = TelefonoClientetxt.getText();
        direccion = DireccionClientetxt.getText();
        libretaSQL.ActualizarLibretaCliente(nombres, apellidos, nombres, telefonocasa, direccion, id);

    }//GEN-LAST:event_ActualizarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizarbtn;
    private javax.swing.JTextField ApellidoClientetxt;
    private javax.swing.JButton Buscarbtn;
    private javax.swing.JTextField CelularClientetxt;
    private javax.swing.JTextField DireccionClientetxt;
    private javax.swing.JButton Eliminarbtn;
    private javax.swing.JButton GuardarClientebtn;
    private javax.swing.JTextField NombreClientetxt;
    private javax.swing.JButton Regresarbtn;
    private javax.swing.JTextField TelefonoClientetxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
