/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteContraseña;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import ClasesInterfaz.ComponenteRadioButon;
import ClasesSQL.MercaderiaSQL;
import ClasesSQL.PersonalSQL;
import ClasesSQL.UsuarioSQL;
import Usuario.Compresor;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author jenif
 */
public class DetallePersonal extends javax.swing.JFrame {

    int IdUsuario = 0;

    String Usuario = "", Nit = "", CUI = "", Direccion = "", Telefono = "", Profesion = "", FechaDeNacimiento = "", Edad = "", FechaDeIngreso = "", TipoDeSangre = "", Alergias = "", Enfermedad = "", Contacto = "", Sueldo = "", Medicamento = "";
    Password contraseña3;
    String pass_concatenada = "", pass_concatenada2 = "";
    boolean verificacion;
    Compresor compresor = new Compresor();
    UsuarioSQL usuarioSQL = new UsuarioSQL();
    PersonalSQL personalSQL = new PersonalSQL();
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();
    ComponenteContraseña password = new ComponenteContraseña();
    ComponenteRadioButon radio = new ComponenteRadioButon();
    ArrayList<String> listapuesto = usuarioSQL.SeleccionarPuestos();
    MercaderiaSQL mercaderiasql = new MercaderiaSQL();
    java.util.Date date = new java.util.Date();
    SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form Menu
     */
    public DetallePersonal() {

        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
        PuestoLaboralcmbx1.addItem("A positivo (A+)");
        PuestoLaboralcmbx1.addItem("A negativo (A-)");
        PuestoLaboralcmbx1.addItem("B positivo (B+)");
        PuestoLaboralcmbx1.addItem("B negativo (B-)");
        PuestoLaboralcmbx1.addItem("AB positivo (AB+)");
        PuestoLaboralcmbx1.addItem("AB negativo (AB-)");
        PuestoLaboralcmbx1.addItem("O positivo (O+)");
        PuestoLaboralcmbx1.addItem("O negativo (O-)");
        try {
            /*  for (String nombrepuesto : listapuesto) {
            PuestoLaboralcmbx.addItem(nombrepuesto);
            }*/
            mercaderiasql.ConsultaDeUsuario(PuestoLaboralcmbx);
        } catch (SQLException ex) {
            Logger.getLogger(DetallePersonal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void transparenciButton() {
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        String texto5 = "Regresar a Ingreso De Trabajador";
        jButton3.setToolTipText(texto5);
        String texto3 = "Guardar Detalle";
        CrearCuentabtn.setToolTipText(texto3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Usuariotxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ApellidoColaboradortxt = new javax.swing.JTextField();
        NombreColaboradortxt = new javax.swing.JTextField();
        PuestoLaboralcmbx = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        NombreColaboradortxt1 = new javax.swing.JTextField();
        ApellidoColaboradortxt1 = new javax.swing.JTextField();
        NombreColaboradortxt2 = new javax.swing.JTextField();
        NombreColaboradortxt3 = new javax.swing.JTextField();
        PuestoLaboralcmbx1 = new javax.swing.JComboBox<>();
        NombreColaboradortxt4 = new javax.swing.JTextField();
        FechaCalendar2 = new com.toedter.calendar.JCalendar();
        FechaCalendar3 = new com.toedter.calendar.JCalendar();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        NombreColaboradortxt5 = new javax.swing.JTextField();
        NombreColaboradortxt6 = new javax.swing.JTextField();
        CrearCuentabtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 181, 114));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(249, 181, 114));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        Usuariotxt.setBackground(new java.awt.Color(236, 255, 224));
        Usuariotxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Usuariotxt.setForeground(new java.awt.Color(102, 102, 102));
        Usuariotxt.setText("Dirección");
        Usuariotxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Usuariotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariotxtActionPerformed(evt);
            }
        });
        Usuariotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuariotxtKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Detalle Colaborador");

        ApellidoColaboradortxt.setBackground(new java.awt.Color(236, 255, 224));
        ApellidoColaboradortxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        ApellidoColaboradortxt.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoColaboradortxt.setText("CUI");
        ApellidoColaboradortxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ApellidoColaboradortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoColaboradortxtActionPerformed(evt);
            }
        });
        ApellidoColaboradortxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ApellidoColaboradortxtKeyPressed(evt);
            }
        });

        NombreColaboradortxt.setBackground(new java.awt.Color(236, 255, 224));
        NombreColaboradortxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreColaboradortxt.setForeground(new java.awt.Color(102, 102, 102));
        NombreColaboradortxt.setText("Nit");
        NombreColaboradortxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreColaboradortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreColaboradortxtActionPerformed(evt);
            }
        });
        NombreColaboradortxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreColaboradortxtKeyPressed(evt);
            }
        });

        PuestoLaboralcmbx.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        PuestoLaboralcmbx.setForeground(new java.awt.Color(102, 102, 102));
        PuestoLaboralcmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario" }));
        PuestoLaboralcmbx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        NombreColaboradortxt1.setBackground(new java.awt.Color(236, 255, 224));
        NombreColaboradortxt1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreColaboradortxt1.setForeground(new java.awt.Color(102, 102, 102));
        NombreColaboradortxt1.setText("Edad");
        NombreColaboradortxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreColaboradortxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreColaboradortxt1ActionPerformed(evt);
            }
        });
        NombreColaboradortxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreColaboradortxt1KeyPressed(evt);
            }
        });

        ApellidoColaboradortxt1.setBackground(new java.awt.Color(236, 255, 224));
        ApellidoColaboradortxt1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        ApellidoColaboradortxt1.setForeground(new java.awt.Color(102, 102, 102));
        ApellidoColaboradortxt1.setText("Profesión");
        ApellidoColaboradortxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ApellidoColaboradortxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoColaboradortxt1ActionPerformed(evt);
            }
        });
        ApellidoColaboradortxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ApellidoColaboradortxt1KeyPressed(evt);
            }
        });

        NombreColaboradortxt2.setBackground(new java.awt.Color(236, 255, 224));
        NombreColaboradortxt2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreColaboradortxt2.setForeground(new java.awt.Color(102, 102, 102));
        NombreColaboradortxt2.setText("Teléfono");
        NombreColaboradortxt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreColaboradortxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreColaboradortxt2ActionPerformed(evt);
            }
        });
        NombreColaboradortxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreColaboradortxt2KeyPressed(evt);
            }
        });

        NombreColaboradortxt3.setBackground(new java.awt.Color(236, 255, 224));
        NombreColaboradortxt3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreColaboradortxt3.setForeground(new java.awt.Color(102, 102, 102));
        NombreColaboradortxt3.setText("Alergias");
        NombreColaboradortxt3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreColaboradortxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreColaboradortxt3ActionPerformed(evt);
            }
        });
        NombreColaboradortxt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreColaboradortxt3KeyPressed(evt);
            }
        });

        PuestoLaboralcmbx1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        PuestoLaboralcmbx1.setForeground(new java.awt.Color(102, 102, 102));
        PuestoLaboralcmbx1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Sangre" }));
        PuestoLaboralcmbx1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        NombreColaboradortxt4.setBackground(new java.awt.Color(236, 255, 224));
        NombreColaboradortxt4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreColaboradortxt4.setForeground(new java.awt.Color(102, 102, 102));
        NombreColaboradortxt4.setText("Enfermedad");
        NombreColaboradortxt4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreColaboradortxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreColaboradortxt4ActionPerformed(evt);
            }
        });
        NombreColaboradortxt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreColaboradortxt4KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Fecha de Nacimiento");

        jLabel15.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Fecha de Ingreso");

        NombreColaboradortxt5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreColaboradortxt5.setForeground(new java.awt.Color(102, 102, 102));
        NombreColaboradortxt5.setText("Contacto");
        NombreColaboradortxt5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreColaboradortxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreColaboradortxt5ActionPerformed(evt);
            }
        });
        NombreColaboradortxt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreColaboradortxt5KeyPressed(evt);
            }
        });

        NombreColaboradortxt6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreColaboradortxt6.setForeground(new java.awt.Color(102, 102, 102));
        NombreColaboradortxt6.setText("Sueldo");
        NombreColaboradortxt6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreColaboradortxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreColaboradortxt6ActionPerformed(evt);
            }
        });
        NombreColaboradortxt6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreColaboradortxt6KeyPressed(evt);
            }
        });

        CrearCuentabtn.setBackground(new java.awt.Color(211, 84, 0));
        CrearCuentabtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        CrearCuentabtn.setForeground(new java.awt.Color(255, 255, 255));
        CrearCuentabtn.setText("GUARDAR");
        CrearCuentabtn.setBorder(null);
        CrearCuentabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearCuentabtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        CrearCuentabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreColaboradortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PuestoLaboralcmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoColaboradortxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreColaboradortxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(NombreColaboradortxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApellidoColaboradortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PuestoLaboralcmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreColaboradortxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreColaboradortxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreColaboradortxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(FechaCalendar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NombreColaboradortxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(CrearCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PuestoLaboralcmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PuestoLaboralcmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreColaboradortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoColaboradortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(NombreColaboradortxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NombreColaboradortxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ApellidoColaboradortxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreColaboradortxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreColaboradortxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaCalendar3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreColaboradortxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreColaboradortxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CrearCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariotxtActionPerformed

    private void UsuariotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuariotxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Direccion = Usuariotxt.getText();
            //    usuarioSQL.ComparacioConOtroUsuarios(usuario);
        }
    }//GEN-LAST:event_UsuariotxtKeyPressed

    private void CrearCuentabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentabtnActionPerformed
        // TODO add your handling code here:
        Usuario = "Prueba3";
        Nit = "535345k";
        CUI = "A4534H43443";
        Direccion = "Quetzaltenango";
        Telefono = "5345345";
        Profesion = "Secretaria";
        FechaDeNacimiento = "2023-06-06";
        Edad = "44";
        FechaDeIngreso = "2023-06-06";
        TipoDeSangre = "A Positivo";
        Alergias = "Ninguna";
        Enfermedad = "Ninguna";
        Contacto = "5353453";
        Sueldo = "3000";

        Medicamento = "Ninguno";

        Usuario = (String) PuestoLaboralcmbx.getSelectedItem();
        TipoDeSangre = (String) PuestoLaboralcmbx1.getSelectedItem();
        Nit = NombreColaboradortxt.getText();
        CUI = ApellidoColaboradortxt.getText();
        Direccion = Usuariotxt.getText();
        Telefono = NombreColaboradortxt2.getText();
        Profesion = ApellidoColaboradortxt1.getText();
        Edad = NombreColaboradortxt1.getText();
        Enfermedad = NombreColaboradortxt4.getText();
        Alergias = NombreColaboradortxt3.getText();
        FechaDeNacimiento = f.format(FechaCalendar2.getDate());
        FechaDeIngreso = f.format(FechaCalendar3.getDate());
        Contacto = NombreColaboradortxt5.getText();
        Sueldo = NombreColaboradortxt6.getText();

     /*   System.out.println(Usuario);
        System.out.println(TipoDeSangre);
        System.out.println(Nit);
        System.out.println(CUI);
        System.out.println(Direccion);
        System.out.println(Telefono);
        System.out.println(Profesion);
        System.out.println(Edad);
        System.out.println(Enfermedad);
        System.out.println(Alergias);
        System.out.println(FechaDeNacimiento);
        System.out.println(FechaDeIngreso);
        System.out.println(Contacto);
        System.out.println(Sueldo);
        System.out.println(Medicamento);*/
        personalSQL.InsertarPersonal(Usuario, Nit, CUI, Direccion, Telefono, Profesion, FechaDeNacimiento, Edad, FechaDeIngreso, TipoDeSangre, Alergias, Enfermedad, Contacto, Sueldo, Medicamento);

    }//GEN-LAST:event_CrearCuentabtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Colaborador ingreso = new Colaborador();
        ingreso.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ApellidoColaboradortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoColaboradortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoColaboradortxtActionPerformed

    private void ApellidoColaboradortxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoColaboradortxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CUI = ApellidoColaboradortxt.getText();
        }
    }//GEN-LAST:event_ApellidoColaboradortxtKeyPressed

    private void NombreColaboradortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreColaboradortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxtActionPerformed

    private void NombreColaboradortxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreColaboradortxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Nit = NombreColaboradortxt.getText();
        }
    }//GEN-LAST:event_NombreColaboradortxtKeyPressed
    boolean modoOscuro = false;

    private void Pintar(Color colorbotones, String imagen, Color colortexto, Color colorlabel, Color colorbase, Color colorfondo, Color colorcontraseña) {

    }
    private void NombreColaboradortxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreColaboradortxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxt1ActionPerformed

    private void NombreColaboradortxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreColaboradortxt1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Edad = NombreColaboradortxt1.getText();
        }
    }//GEN-LAST:event_NombreColaboradortxt1KeyPressed

    private void ApellidoColaboradortxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoColaboradortxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoColaboradortxt1ActionPerformed

    private void ApellidoColaboradortxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoColaboradortxt1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Profesion = ApellidoColaboradortxt1.getText();
        }
    }//GEN-LAST:event_ApellidoColaboradortxt1KeyPressed

    private void NombreColaboradortxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreColaboradortxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxt2ActionPerformed

    private void NombreColaboradortxt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreColaboradortxt2KeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Telefono = NombreColaboradortxt2.getText();
        }
    }//GEN-LAST:event_NombreColaboradortxt2KeyPressed

    private void NombreColaboradortxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreColaboradortxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxt3ActionPerformed

    private void NombreColaboradortxt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreColaboradortxt3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Alergias = NombreColaboradortxt3.getText();
        }
    }//GEN-LAST:event_NombreColaboradortxt3KeyPressed

    private void NombreColaboradortxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreColaboradortxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxt4ActionPerformed

    private void NombreColaboradortxt4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreColaboradortxt4KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Enfermedad = NombreColaboradortxt4.getText();
        }
    }//GEN-LAST:event_NombreColaboradortxt4KeyPressed

    private void NombreColaboradortxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreColaboradortxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxt5ActionPerformed

    private void NombreColaboradortxt5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreColaboradortxt5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxt5KeyPressed

    private void NombreColaboradortxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreColaboradortxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxt6ActionPerformed

    private void NombreColaboradortxt6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreColaboradortxt6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreColaboradortxt6KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallePersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallePersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallePersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallePersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallePersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoColaboradortxt;
    private javax.swing.JTextField ApellidoColaboradortxt1;
    private javax.swing.JButton CrearCuentabtn;
    private com.toedter.calendar.JCalendar FechaCalendar2;
    private com.toedter.calendar.JCalendar FechaCalendar3;
    private javax.swing.JTextField NombreColaboradortxt;
    private javax.swing.JTextField NombreColaboradortxt1;
    private javax.swing.JTextField NombreColaboradortxt2;
    private javax.swing.JTextField NombreColaboradortxt3;
    private javax.swing.JTextField NombreColaboradortxt4;
    private javax.swing.JTextField NombreColaboradortxt5;
    private javax.swing.JTextField NombreColaboradortxt6;
    private javax.swing.JComboBox<String> PuestoLaboralcmbx;
    private javax.swing.JComboBox<String> PuestoLaboralcmbx1;
    private javax.swing.JTextField Usuariotxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
