/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Dimensional;
import Clases.InsumoUso;
import Clases.Usuario;
import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import ClasesInterfaz.ComponenteRadioButon;
import ClasesSQL.DimensionalSQL;
import ClasesSQL.MedicamentosYAlimentosSQL;
import ClasesSQL.MostrarEnInterfaces;
import ClasesSQL.ProveedorSQL;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import sun.security.util.Password;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author jenif
 */
public class MedicamentosYAlimentos extends javax.swing.JFrame {

    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    boolean medicamento, alimento, vacuna, inmunizador, vitamina, conceEngorde, conceCrecimiento, maiz;
    String nombreproveedor = "", tipoproducto = "", nombreProducto = "", nombreAlimento = "", tipoDimensional = "";
    ProveedorSQL SQLproveedores = new ProveedorSQL();
    DimensionalSQL SQLDimensionales = new DimensionalSQL();
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();
    ComponenteRadioButon radio = new ComponenteRadioButon();
    Clases.InsumoConsumo insumoconsumo = new Clases.InsumoConsumo();
    Clases.Dimensional dimensional = new Clases.Dimensional();
    Clases.Proveedor proveedor = new Clases.Proveedor();
    Clases.Usuario usuario = new Clases.Usuario();
    ArrayList<Clases.Proveedor> listaProveedores = SQLproveedores.ConsultaProveedorNombre();
    ArrayList<Clases.Dimensional> listaDimensionales = SQLDimensionales.ConsultaDimencional();
    MedicamentosYAlimentosSQL SQLInsumoConsumo = new MedicamentosYAlimentosSQL();

    /*crud thecrud = new crud();
    Connection con = (Connection) ConexionBD.GetConnection();*/
    /**
     * Creates new form Menu
     */
    public MedicamentosYAlimentos(Usuario usuario) {

        //     this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
        for (Clases.Proveedor prov : listaProveedores) {
            Proveedorjcmb.addItem(prov.getNombre());
        }
        for (Clases.Dimensional dim : listaDimensionales) {
            Dimensionaljcmb.addItem(dim.getDimensional());
        }
        this.usuario = usuario;
    }

    public MedicamentosYAlimentos() {

//        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();

        for (Clases.Proveedor prov : listaProveedores) {
            Proveedorjcmb.addItem(prov.getNombre());
        }

        for (Clases.Dimensional dim : listaDimensionales) {
            Dimensionaljcmb.addItem(dim.getDimensional());
        }
    }

    public void transparenciButton() {
        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        AgregarDimensionalbtn.setOpaque(false);
        AgregarDimensionalbtn.setContentAreaFilled(false);
        AgregarDimensionalbtn.setBorderPainted(false);
        String texto2 = "Regresar a Menú Principal";
        jButton4.setToolTipText(texto2);
        String texto3 = "Agregar otra Dimesional";
        AgregarDimensionalbtn.setToolTipText(texto3);
        String texto4 = "Guardar Insumo";
        Guardarbtn.setToolTipText(texto4);
        String texto5 = "Haga click para acceder a Eliminación de Insumo";
        Guardarbtn1.setToolTipText(texto5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoInsumo = new javax.swing.ButtonGroup();
        Medicamentos = new javax.swing.ButtonGroup();
        Alimentos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Guardarbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Cantidadtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Totaltxt = new javax.swing.JTextField();
        Medicamentosrbtn = new javax.swing.JRadioButton();
        Alimentosrbtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Inmunizadorrbtn = new javax.swing.JRadioButton();
        ConCrecimientorbtn = new javax.swing.JRadioButton();
        FechaCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel14 = new javax.swing.JLabel();
        FechaCalendar2 = new com.toedter.calendar.JCalendar();
        jLabel3 = new javax.swing.JLabel();
        Maizrbtn = new javax.swing.JRadioButton();
        Vitaminarbtn = new javax.swing.JRadioButton();
        Vacunarbtn = new javax.swing.JRadioButton();
        ConEngorderbtn = new javax.swing.JRadioButton();
        Dimensionaljcmb = new javax.swing.JComboBox<>();
        AgregarDimensionalbtn = new javax.swing.JButton();
        Proveedorjcmb = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        Guardarbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 125, 125));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Guardarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Guardarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Guardarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Guardarbtn.setText("Guardar");
        Guardarbtn.setBorder(null);
        Guardarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Guardarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 144, 34));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicamento.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        Cantidadtxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Cantidadtxt.setForeground(new java.awt.Color(102, 102, 102));
        Cantidadtxt.setText("Cantidad");
        Cantidadtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cantidadtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cantidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadtxtActionPerformed(evt);
            }
        });
        Cantidadtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CantidadtxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadtxtKeyTyped(evt);
            }
        });
        jPanel2.add(Cantidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 253, 43));

        jLabel7.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Tipo de Insumo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Fecha de Vencimiento");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, 20));

        Totaltxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Totaltxt.setForeground(new java.awt.Color(102, 102, 102));
        Totaltxt.setText("Total");
        Totaltxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Totaltxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotaltxtActionPerformed(evt);
            }
        });
        Totaltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TotaltxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TotaltxtKeyTyped(evt);
            }
        });
        jPanel2.add(Totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 253, 43));

        Medicamentosrbtn.setBackground(new java.awt.Color(255, 255, 255));
        TipoInsumo.add(Medicamentosrbtn);
        Medicamentosrbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Medicamentosrbtn.setForeground(new java.awt.Color(51, 51, 51));
        Medicamentosrbtn.setText("Medicamentos");
        Medicamentosrbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Medicamentosrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicamentosrbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Medicamentosrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        Alimentosrbtn.setBackground(new java.awt.Color(255, 255, 255));
        TipoInsumo.add(Alimentosrbtn);
        Alimentosrbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Alimentosrbtn.setForeground(new java.awt.Color(51, 51, 51));
        Alimentosrbtn.setText("Alimentos");
        Alimentosrbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Alimentosrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlimentosrbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Alimentosrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/harina-de-maiz.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Tipo de Medicamento");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Tipo de Alimento");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        Inmunizadorrbtn.setBackground(new java.awt.Color(255, 255, 255));
        Medicamentos.add(Inmunizadorrbtn);
        Inmunizadorrbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Inmunizadorrbtn.setForeground(new java.awt.Color(51, 51, 51));
        Inmunizadorrbtn.setText("Inmunizador");
        Inmunizadorrbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Inmunizadorrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InmunizadorrbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Inmunizadorrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        ConCrecimientorbtn.setBackground(new java.awt.Color(255, 255, 255));
        Alimentos.add(ConCrecimientorbtn);
        ConCrecimientorbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        ConCrecimientorbtn.setForeground(new java.awt.Color(51, 51, 51));
        ConCrecimientorbtn.setText("Concentrado de crecimiento");
        ConCrecimientorbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(ConCrecimientorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));
        jPanel2.add(FechaCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, 125));

        jLabel14.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Fecha de Ingreso");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));
        jPanel2.add(FechaCalendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 125));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("MEDICAMENTOS Y ALIMENTOS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 24, -1, -1));

        Maizrbtn.setBackground(new java.awt.Color(255, 255, 255));
        Alimentos.add(Maizrbtn);
        Maizrbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Maizrbtn.setForeground(new java.awt.Color(51, 51, 51));
        Maizrbtn.setText("Maiz");
        Maizrbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Maizrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        Vitaminarbtn.setBackground(new java.awt.Color(255, 255, 255));
        Medicamentos.add(Vitaminarbtn);
        Vitaminarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Vitaminarbtn.setForeground(new java.awt.Color(51, 51, 51));
        Vitaminarbtn.setText("Vitamina");
        Vitaminarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Vitaminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitaminarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Vitaminarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        Vacunarbtn.setBackground(new java.awt.Color(255, 255, 255));
        Medicamentos.add(Vacunarbtn);
        Vacunarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Vacunarbtn.setForeground(new java.awt.Color(51, 51, 51));
        Vacunarbtn.setText("Vacuna");
        Vacunarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Vacunarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacunarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Vacunarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        ConEngorderbtn.setBackground(new java.awt.Color(255, 255, 255));
        Alimentos.add(ConEngorderbtn);
        ConEngorderbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        ConEngorderbtn.setForeground(new java.awt.Color(51, 51, 51));
        ConEngorderbtn.setText("Concentrado de engorde ");
        ConEngorderbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(ConEngorderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        Dimensionaljcmb.setBackground(new java.awt.Color(244, 253, 251));
        Dimensionaljcmb.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        Dimensionaljcmb.setForeground(new java.awt.Color(51, 51, 51));
        Dimensionaljcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DimensionaljcmbActionPerformed(evt);
            }
        });
        jPanel2.add(Dimensionaljcmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 140, 40));

        AgregarDimensionalbtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AgregarDimensionalbtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregarDimensionalbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas.png"))); // NOI18N
        AgregarDimensionalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDimensionalbtnActionPerformed(evt);
            }
        });
        jPanel2.add(AgregarDimensionalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 40, -1));

        Proveedorjcmb.setBackground(new java.awt.Color(244, 253, 251));
        Proveedorjcmb.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Proveedorjcmb.setForeground(new java.awt.Color(102, 102, 102));
        Proveedorjcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor", " ", " " }));
        Proveedorjcmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Proveedorjcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorjcmbActionPerformed(evt);
            }
        });
        jPanel2.add(Proveedorjcmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 250, 40));

        jButton4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 50, -1));

        Guardarbtn1.setBackground(new java.awt.Color(211, 84, 0));
        Guardarbtn1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Guardarbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Guardarbtn1.setText("Eliminar");
        Guardarbtn1.setBorder(null);
        Guardarbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardarbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardarbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(Guardarbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 144, 34));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Menu3 menux = new Menu3();
        menux.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ProveedorjcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorjcmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveedorjcmbActionPerformed

    private void AgregarDimensionalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDimensionalbtnActionPerformed
        // TODO add your handling code here:
        tipoDimensional = JOptionPane.showInputDialog("Ingrese Producto");
        Dimensionaljcmb.addItem(tipoDimensional);
        SQLDimensionales.InsertarDimensional(tipoDimensional);
        /*listaDimensionales = SQLDimensionales.ConsultaDimencional();
        for (Clases.Dimensional dim : listaDimensionales) {
            Dimensionaljcmb.addItem(dim.getDimensional());
        }*/
    }//GEN-LAST:event_AgregarDimensionalbtnActionPerformed

    private void DimensionaljcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DimensionaljcmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DimensionaljcmbActionPerformed

    private void VacunarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacunarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VacunarbtnActionPerformed

    private void VitaminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitaminarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VitaminarbtnActionPerformed

    private void InmunizadorrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InmunizadorrbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InmunizadorrbtnActionPerformed

    private void TotaltxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotaltxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            System.out.println("df");
        }
    }//GEN-LAST:event_TotaltxtKeyPressed

    private void TotaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotaltxtActionPerformed

    private void CantidadtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadtxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("hh");
        }
    }//GEN-LAST:event_CantidadtxtKeyPressed

    private void CantidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadtxtActionPerformed

    private void GuardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarbtnActionPerformed
        listaProveedores = SQLproveedores.ConsultaProveedorNombre();
        listaDimensionales = SQLDimensionales.ConsultaDimencional();

        InsumoUso datos = new InsumoUso();
        if (Medicamentosrbtn.isSelected()) {
            medicamento = true;
            tipoproducto = "Medicamentos";
            System.out.println("Tipo Medicamento" + tipoproducto);

            if (Vacunarbtn.isSelected()) {
                vacuna = true;
                nombreProducto = "Vacuna";
                System.out.println("Nombre Medicamento" + nombreProducto);

            }
            if (Inmunizadorrbtn.isSelected()) {
                inmunizador = true;
                nombreProducto = "Inmunizador";
                System.out.println("Nombre Medicamento" + nombreProducto);
            }
            if (Vitaminarbtn.isSelected()) {
                vitamina = true;
                nombreProducto = "Vitamina";
                System.out.println("Nombre Medicamento" + nombreProducto);
            }
        } else {
            medicamento = false;
        }

        if (Alimentosrbtn.isSelected()) {
            alimento = true;
            tipoproducto = "Alimentos";
            System.out.println("Tipo Medicamento" + tipoproducto);

            if (ConEngorderbtn.isSelected()) {
                conceEngorde = true;
                nombreAlimento = "Concentrado de Engorde";
                System.out.println("Tipo Medicamento" + nombreAlimento);
            }
            if (ConCrecimientorbtn.isSelected()) {
                conceCrecimiento = true;
                nombreAlimento = "Concentrado de Crecimiento";
                System.out.println("Tipo Medicamento" + nombreAlimento);
            }
            if (Maizrbtn.isSelected()) {
                maiz = true;
                nombreAlimento = "Maiz";
                System.out.println("Tipo Medicamento" + nombreAlimento);
            }

        } else {
            alimento = false;
        }
        String fechaIngreso = formato.format(FechaCalendar2.getDate());
        String fechaVencimiento = formato.format(FechaCalendar1.getDate());
        for (Clases.Proveedor prov : listaProveedores) {
            proveedor.setNombre((String) Proveedorjcmb.getSelectedItem());
            if (proveedor.getNombre().equals(prov.getNombre())) {
                proveedor.setIdProveedor(prov.getIdProveedor());
            }
        }
        for (Clases.Dimensional dim : listaDimensionales) {
            dimensional.setDimensional((String) Dimensionaljcmb.getSelectedItem());
            if (dimensional.getDimensional().equals(dim.getDimensional())) {
                dimensional.setIdDimensional(dim.getIdDimensional());
            }
        }

        insumoconsumo.setTipoInsumo(tipoproducto);
        if (alimento == false) {
            insumoconsumo.setNombre(nombreProducto);
        } else if (medicamento == false) {
            insumoconsumo.setNombre(nombreAlimento);
        }
        insumoconsumo.setExistencia(Integer.parseInt(Cantidadtxt.getText()));
        insumoconsumo.setTotal(Float.parseFloat(Totaltxt.getText()));
        insumoconsumo.setFechaIngreso(fechaIngreso);
        insumoconsumo.setFechaVencimiento(fechaVencimiento);
        insumoconsumo.setDimensional(dimensional);
        insumoconsumo.setProveedor(proveedor);
        insumoconsumo.setUsuario(usuario);
        System.out.println("Tipo" + insumoconsumo);
        System.out.println(Cantidadtxt.getText());
        System.out.println(Totaltxt.getText());
        System.out.println(fechaIngreso);
        System.out.println(fechaVencimiento);
        System.out.println(dimensional);
        System.out.println(proveedor);
        System.out.println(usuario);
        SQLInsumoConsumo.InsertarMedicamentosYAlimentos(insumoconsumo);
        Cantidadtxt.setText("Cantidad");
        Totaltxt.setText("Total");
        Proveedorjcmb.setSelectedItem("Proveedor");
        Dimensionaljcmb.setSelectedIndex(0);
        Medicamentosrbtn.setSelected(false);
        Vacunarbtn.setSelected(false);
        FechaCalendar2.setDate(null);
        FechaCalendar1.setDate(null);
        //  SQLInsumoConsumo.InsertarMedicamentosYAlimentos(insumoconsumo,);
    }//GEN-LAST:event_GuardarbtnActionPerformed
    private void Pintar(Color colorbotones, String imagen, Color colortexto, Color colorlabel, Color colorbase, Color colorfondo) {

    }
    private void CantidadtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadtxtKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_CantidadtxtKeyTyped

    private void TotaltxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotaltxtKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TotaltxtKeyTyped

    private void MedicamentosrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicamentosrbtnActionPerformed
        // TODO add your handling code here:
        ConCrecimientorbtn.setEnabled(false);
        ConEngorderbtn.setEnabled(false);
        Maizrbtn.setEnabled(false);
        Vacunarbtn.setEnabled(true);
        Inmunizadorrbtn.setEnabled(true);
        Vitaminarbtn.setEnabled(true);
    }//GEN-LAST:event_MedicamentosrbtnActionPerformed

    private void AlimentosrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlimentosrbtnActionPerformed
        // TODO add your handling code here:
        ConCrecimientorbtn.setEnabled(true);
        ConEngorderbtn.setEnabled(true);
        Maizrbtn.setEnabled(true);
        Vacunarbtn.setEnabled(false);
        Inmunizadorrbtn.setEnabled(false);
        Vitaminarbtn.setEnabled(false);
    }//GEN-LAST:event_AlimentosrbtnActionPerformed

    private void Guardarbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardarbtn1ActionPerformed
        // TODO add your handling code here:
        VerMedAli menux = new VerMedAli();
        menux.setVisible(true);
        dispose();
    }//GEN-LAST:event_Guardarbtn1ActionPerformed
    List Proveedores = new ArrayList();

    static void obtener_proveedor(ArrayList<Integer> id, ArrayList<String> Proveedor) {
        int ID = 0;
        String proveedor = "";
        id.get(ID);
        Proveedor.get(Integer.parseInt(proveedor));
    }
    boolean modoOscuro = false;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicamentosYAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicamentosYAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicamentosYAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicamentosYAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicamentosYAlimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDimensionalbtn;
    private javax.swing.ButtonGroup Alimentos;
    private javax.swing.JRadioButton Alimentosrbtn;
    private javax.swing.JTextField Cantidadtxt;
    private javax.swing.JRadioButton ConCrecimientorbtn;
    private javax.swing.JRadioButton ConEngorderbtn;
    private javax.swing.JComboBox<String> Dimensionaljcmb;
    private com.toedter.calendar.JCalendar FechaCalendar1;
    private com.toedter.calendar.JCalendar FechaCalendar2;
    private javax.swing.JButton Guardarbtn;
    private javax.swing.JButton Guardarbtn1;
    private javax.swing.JRadioButton Inmunizadorrbtn;
    private javax.swing.JRadioButton Maizrbtn;
    private javax.swing.ButtonGroup Medicamentos;
    private javax.swing.JRadioButton Medicamentosrbtn;
    private javax.swing.JComboBox<String> Proveedorjcmb;
    private javax.swing.ButtonGroup TipoInsumo;
    private javax.swing.JTextField Totaltxt;
    private javax.swing.JRadioButton Vacunarbtn;
    private javax.swing.JRadioButton Vitaminarbtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
