/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Usuario;
import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import sun.security.util.Password;

/**
 *
 * @author jenif
 */
public class Menu extends javax.swing.JFrame {

    private boolean modoOscuro;
    int numeromenu;
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();

    /**
     * Creates new form Menu
     */
    public Menu() {

//        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
    }

    public Menu(int numeroboton) {

        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
        nombrarmenu(numeroboton);
        numeromenu = numeroboton;
    }

    public Menu(Usuario usuario) {

        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
    }

    public void transparenciButton() {
        Accion1btn.setOpaque(false);
        Accion1btn.setContentAreaFilled(false);
        Accion1btn.setBorderPainted(false);
        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setBorderPainted(false);
        Accion2btn.setOpaque(false);
        Accion2btn.setContentAreaFilled(false);
        Accion2btn.setBorderPainted(false);
        String texto2 = "Agregar Cliente";
        Accion1btn.setToolTipText(texto2);
        String texto3 = "Ver Libreta";
        Accion2btn.setToolTipText(texto3);
        String texto4 = "Regresar a Menú Principal";
        jButton8.setToolTipText(texto4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        Accion2btn = new javax.swing.JButton();
        Accion1btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 186));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 125, 125));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(102, 102, 102));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        Accion2btn.setBackground(new java.awt.Color(0, 0, 102));
        Accion2btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Accion2btn.setForeground(new java.awt.Color(102, 102, 102));
        Accion2btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agenda (1).png"))); // NOI18N
        Accion2btn.setText("Clientes");
        Accion2btn.setActionCommand("Clientes");
        Accion2btn.setBorder(null);
        Accion2btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Accion2btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Accion2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accion2btnActionPerformed(evt);
            }
        });

        Accion1btn.setBackground(new java.awt.Color(0, 0, 102));
        Accion1btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Accion1btn.setForeground(new java.awt.Color(102, 102, 102));
        Accion1btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ninos (1)_1.png"))); // NOI18N
        Accion1btn.setText("Añadir Cliente");
        Accion1btn.setBorder(null);
        Accion1btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Accion1btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Accion1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accion1btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Accion1btn, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(Accion2btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton8))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(Accion1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Accion2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Accion2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accion2btnActionPerformed
        // TODO add your handling code here:
        VistaLibretaClientes cliente = new VistaLibretaClientes();
        cliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_Accion2btnActionPerformed

    private void Accion1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accion1btnActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
        dispose();
        //direccionarmenu(numeromenu, 1);

    }//GEN-LAST:event_Accion1btnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Menu3 menu = new Menu3();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed
    private void Pintar(Color colorbotones, String imagen, Color colorfondo) {

        panel.setPanelFondo(jPanel1);
        panel.setColorFondo(colorfondo);
        panel.getPanelFondo();
        boton.setBoton(Accion1btn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(Accion2btn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();

    }

    private void nombrarmenu(int numeromenu) {
        if (numeromenu == 1) {
            Accion1btn.setText("AGREGAR CLIENTE");
            Accion2btn.setText("VER LIBRETA");

        }/* else if (numeromenu == 2) {
            Accion1btn.setText("CREAR CUENTA");
            Accion2btn.setText("VER COLABORADORES");
        }*/ else if (numeromenu == 3) {
            Accion1btn.setText("CREAR PROVEEDOR");
            Accion2btn.setText("VER PROVEEDORES");
        } else if (numeromenu == 4) {
            Accion1btn.setText("AÑADIR MERCADERIA");
            Accion2btn.setText("GENERAR VENTA");
        }

    }

    private void direccionarmenu(int numeromenu, int accion) {
        if (numeromenu == 1) {
            if (accion == 1) {
                Cliente cliente = new Cliente();
                cliente.setVisible(true);
                dispose();
            } else if (accion == 2) {
                Libreta libreta = new Libreta();
                libreta.setVisible(true);
                dispose();
            }
        } /*else if (numeromenu == 2) {
            if (accion == 1) {
                CrearCuenta crearcuenta = new CrearCuenta();
                crearcuenta.setVisible(true);
                dispose();
            } else if (accion == 2) {
                Colaborador colaborador = new Colaborador();
                colaborador.setVisible(true);
                dispose();
            }
        }*/ else if (numeromenu == 3) {
            if (accion == 1) {
                Proveedor proveedor = new Proveedor();
                proveedor.setVisible(true);
                dispose();
            } else if (accion == 2) {
                ProveedorVista proveedor = new ProveedorVista();
                proveedor.setVisible(true);
                dispose();
            }
        } else if (numeromenu == 4) {
            if (accion == 1) {
                Mercaderia mercaderia = new Mercaderia();
                mercaderia.setVisible(true);
                dispose();
            } else if (accion == 2) {
                Ventas venta = new Ventas();
                venta.setVisible(true);
                dispose();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accion1btn;
    private javax.swing.JButton Accion2btn;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
