package Interfaz;

import Clases.Usuario;
import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import sun.security.util.Password;

public class Menu3 extends javax.swing.JFrame {

    private boolean modoOscuro;
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();
    Usuario usuario = new Usuario();

    /**
     * Creates new form Menu
     */
    public Menu3() {

        //this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
    }

    public Menu3(Usuario usuario) {

        //this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
        this.usuario = usuario;
    }

    public void transparenciButton() {
        Clientebtn.setOpaque(false);
        Clientebtn.setContentAreaFilled(false);
        Clientebtn.setBorderPainted(false);
        InsumoConsumobtn.setOpaque(false);
        InsumoConsumobtn.setContentAreaFilled(false);
        InsumoConsumobtn.setBorderPainted(false);
        InsumoUsobtn.setOpaque(false);
        InsumoUsobtn.setContentAreaFilled(false);
        InsumoUsobtn.setBorderPainted(false);
        Proveedorbtn.setOpaque(false);
        Proveedorbtn.setContentAreaFilled(false);
        Proveedorbtn.setBorderPainted(false);
        Ventabtn.setOpaque(false);
        Ventabtn.setContentAreaFilled(false);
        Ventabtn.setBorderPainted(false);
        Usuariobtn.setOpaque(false);
        Usuariobtn.setContentAreaFilled(false);
        Usuariobtn.setBorderPainted(false);
        MateriaPrimabtn.setOpaque(false);
        MateriaPrimabtn.setContentAreaFilled(false);
        MateriaPrimabtn.setBorderPainted(false);
        Ventabtn1.setOpaque(false);
        Ventabtn1.setContentAreaFilled(false);
        Ventabtn1.setBorderPainted(false);
        String texto2 = "Cliente";
        Clientebtn.setToolTipText(texto2);
        String texto3 = "Insumo Para Uso";
        InsumoUsobtn.setToolTipText(texto3);
        String texto4 = "Insumo Para Consumo";
        InsumoConsumobtn.setToolTipText(texto4);
        String texto5 = "Materia Prima";
        MateriaPrimabtn.setToolTipText(texto5);
        String texto6 = "Usuario";
        Usuariobtn.setToolTipText(texto6);
        String texto7 = "Venta";
        Ventabtn.setToolTipText(texto7);
        String texto8 = "Proveedor";
        Proveedorbtn.setToolTipText(texto8);
        String texto9 = "Cuentas";
        Ventabtn1.setToolTipText(texto9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Clientebtn = new javax.swing.JButton();
        Ventabtn = new javax.swing.JButton();
        MateriaPrimabtn = new javax.swing.JButton();
        Usuariobtn = new javax.swing.JButton();
        Proveedorbtn = new javax.swing.JButton();
        Ventabtn1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        InsumoUsobtn = new javax.swing.JButton();
        InsumoConsumobtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 604));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 181, 114));
        jPanel1.setForeground(new java.awt.Color(249, 181, 114));

        jPanel2.setBackground(new java.awt.Color(249, 181, 114));

        Clientebtn.setBackground(new java.awt.Color(236, 255, 224));
        Clientebtn.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        Clientebtn.setForeground(new java.awt.Color(102, 102, 102));
        Clientebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        Clientebtn.setText("   CLIENTES");
        Clientebtn.setBorder(null);
        Clientebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clientebtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Clientebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientebtnActionPerformed(evt);
            }
        });

        Ventabtn.setBackground(new java.awt.Color(236, 255, 224));
        Ventabtn.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        Ventabtn.setForeground(new java.awt.Color(102, 102, 102));
        Ventabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bolsa-de-la-compra_2.png"))); // NOI18N
        Ventabtn.setText("VENTAS");
        Ventabtn.setBorder(null);
        Ventabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ventabtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Ventabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentabtnActionPerformed(evt);
            }
        });

        MateriaPrimabtn.setBackground(new java.awt.Color(236, 255, 224));
        MateriaPrimabtn.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        MateriaPrimabtn.setForeground(new java.awt.Color(102, 102, 102));
        MateriaPrimabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pollo-orpington.png"))); // NOI18N
        MateriaPrimabtn.setText(" MATERIA PRIMA");
        MateriaPrimabtn.setBorder(null);
        MateriaPrimabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MateriaPrimabtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        MateriaPrimabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriaPrimabtnActionPerformed(evt);
            }
        });

        Usuariobtn.setBackground(new java.awt.Color(236, 255, 224));
        Usuariobtn.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        Usuariobtn.setForeground(new java.awt.Color(102, 102, 102));
        Usuariobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario22.png"))); // NOI18N
        Usuariobtn.setText("COLABORADORES");
        Usuariobtn.setBorder(null);
        Usuariobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuariobtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Usuariobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariobtnActionPerformed(evt);
            }
        });

        Proveedorbtn.setBackground(new java.awt.Color(236, 255, 224));
        Proveedorbtn.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        Proveedorbtn.setForeground(new java.awt.Color(102, 102, 102));
        Proveedorbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parcela.png"))); // NOI18N
        Proveedorbtn.setText("   PROVEEDORES");
        Proveedorbtn.setBorder(null);
        Proveedorbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Proveedorbtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Proveedorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorbtnActionPerformed(evt);
            }
        });

        Ventabtn1.setBackground(new java.awt.Color(236, 255, 224));
        Ventabtn1.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        Ventabtn1.setForeground(new java.awt.Color(102, 102, 102));
        Ventabtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bolsa-de-la-compra_2.png"))); // NOI18N
        Ventabtn1.setText("CUENTAS");
        Ventabtn1.setBorder(null);
        Ventabtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ventabtn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Ventabtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ventabtn1ActionPerformed(evt);
            }
        });

        InsumoUsobtn.setBackground(new java.awt.Color(236, 255, 224));
        InsumoUsobtn.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        InsumoUsobtn.setForeground(new java.awt.Color(102, 102, 102));
        InsumoUsobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpieza.png"))); // NOI18N
        InsumoUsobtn.setText("INSUMOS DE USO");
        InsumoUsobtn.setBorder(null);
        InsumoUsobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsumoUsobtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        InsumoUsobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsumoUsobtnActionPerformed(evt);
            }
        });

        InsumoConsumobtn.setBackground(new java.awt.Color(236, 255, 224));
        InsumoConsumobtn.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        InsumoConsumobtn.setForeground(new java.awt.Color(102, 102, 102));
        InsumoConsumobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/harina.png"))); // NOI18N
        InsumoConsumobtn.setText("INSUMO CONSUMO");
        InsumoConsumobtn.setBorder(null);
        InsumoConsumobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InsumoConsumobtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        InsumoConsumobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsumoConsumobtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usuariobtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(Proveedorbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Clientebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(MateriaPrimabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator8))
                        .addGap(280, 280, 280))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InsumoConsumobtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(InsumoUsobtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ventabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator9)
                            .addComponent(Ventabtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Usuariobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Clientebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Proveedorbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MateriaPrimabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsumoUsobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsumoConsumobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ventabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ventabtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientebtnActionPerformed
        // TODO add your handling code here:
        /* Libreta cliente = new Libreta();
        cliente.setVisible(true);
        dispose();*/
        Menu menu = new Menu(1);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_ClientebtnActionPerformed

    private void InsumoUsobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsumoUsobtnActionPerformed
        // TODO add your handling code here:
        Inventario inventario = new Inventario();
        inventario.setVisible(true);
        dispose();
    }//GEN-LAST:event_InsumoUsobtnActionPerformed

    private void VentabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentabtnActionPerformed
        // TODO add your handling code here:
        MenuVentas menu = new MenuVentas();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_VentabtnActionPerformed

    private void InsumoConsumobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsumoConsumobtnActionPerformed
        // TODO add your handling code here:
        MedicamentosYAlimentos medicamentosYAlimentos = new MedicamentosYAlimentos(usuario);
        medicamentosYAlimentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_InsumoConsumobtnActionPerformed

    private void MateriaPrimabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriaPrimabtnActionPerformed
        // TODO add your handling code here:
        MenuMateriaPrima materiaPrima = new MenuMateriaPrima(usuario);
        materiaPrima.setVisible(true);
        dispose();
    }//GEN-LAST:event_MateriaPrimabtnActionPerformed

    private void UsuariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariobtnActionPerformed
        // TODO add your handling code here:
        Colaborador colaborador = new Colaborador();
        colaborador.setVisible(true);
        dispose();
    }//GEN-LAST:event_UsuariobtnActionPerformed

    private void ProveedorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorbtnActionPerformed
        // TODO add your handling code here:
        Proveedor proveedor = new Proveedor();
        proveedor.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProveedorbtnActionPerformed

    private void Ventabtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ventabtn1ActionPerformed
        // TODO add your handling code here:
        MenuCuentas proveedor = new MenuCuentas();
        proveedor.setVisible(true);
        dispose();
    }//GEN-LAST:event_Ventabtn1ActionPerformed
    private void Pintar(Color colorbotones, String imagen, Color colorbase, Color colorfondo) {
        panel.setPanelBase(jPanel2);
        panel.setColorBase(colorbase);
        panel.getPanelBase();
        panel.setPanelFondo(jPanel1);
        panel.setColorFondo(colorfondo);
        panel.getPanelFondo();
        boton.setBoton(Clientebtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(InsumoConsumobtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(InsumoUsobtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(MateriaPrimabtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(Usuariobtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(Proveedorbtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(Ventabtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clientebtn;
    private javax.swing.JButton InsumoConsumobtn;
    private javax.swing.JButton InsumoUsobtn;
    private javax.swing.JButton MateriaPrimabtn;
    private javax.swing.JButton Proveedorbtn;
    private javax.swing.JButton Usuariobtn;
    private javax.swing.JButton Ventabtn;
    private javax.swing.JButton Ventabtn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
