/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import ClasesSQL.MateriaPrimaSQL;
import ClasesSQL.MercaderiaSQL;
import ClasesSQL.PruebaSQL;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import sun.security.util.Password;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import sun.security.util.Password;
import ClasesSQL.PruebaSQL;
import ClasesSQL.UpdateMateriaPrimaSQL;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.mail.internet.ParseException;

/**
 *
 * @author jenif
 */
public class Mercaderia extends javax.swing.JFrame {

    PruebaSQL pruebasql = new PruebaSQL();
    MercaderiaSQL mercaderiasql = new MercaderiaSQL();
    UpdateMateriaPrimaSQL SQLupdateMateriaPrima = new UpdateMateriaPrimaSQL();
    LotePollo lote = new LotePollo();
    String proveedor = "", producto = "", loteAverio = "", fecha;
    String nombreproveedor = "", agregarProducto = "", fecha1;
    int cantidad = 0, stock = 0;
    float total;
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();
    MateriaPrimaSQL SQLlamateriaprima = new MateriaPrimaSQL();
    ArrayList<Clases.MateriaPrima> listaMateriaPrima = SQLlamateriaprima.ConsultaMateraPrimaCodigo();
    Clases.MateriaPrima materiaprima = new Clases.MateriaPrima();

    public Mercaderia() {

        //  this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
        Productojcmb.addItem("Pierna");
        Productojcmb.addItem("Ala");
        Productojcmb.addItem("Cuadril");
        Productojcmb.addItem("Pechuga");
        Productojcmb.addItem("Menudo");
        for (Clases.MateriaPrima materia : listaMateriaPrima) {
            Productojcmb1.addItem(materia.getLoteAverio());
        }
    }

    public void transparenciButton() {
        AgregaMercaderiabtn.setOpaque(false);
        AgregaMercaderiabtn.setContentAreaFilled(false);
        AgregaMercaderiabtn.setBorderPainted(false);
        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        String texto8 = "Agregar Pieza";
        AgregaMercaderiabtn.setToolTipText(texto8);
        String texto9 = "Guardar Mercadería";
        Guardarbtn.setToolTipText(texto9);
        String texto1 = "Regresar a Menú Principal";
        jButton4.setToolTipText(texto1);
        String texto5 = "Haga click para acceder a Eliminación de Mercadería";
        Actualizarbtn.setToolTipText(texto5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Actualizarbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Guardarbtn = new javax.swing.JButton();
        Cantidadtxt = new javax.swing.JTextField();
        Productojcmb = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Totaltxt = new javax.swing.JTextField();
        FechaCalendar2 = new com.toedter.calendar.JCalendar();
        Stocktxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AgregaMercaderiabtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Productojcmb1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 125, 125));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Actualizarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Actualizarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Actualizarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Actualizarbtn.setText("Eliminar");
        Actualizarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Actualizarbtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Actualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Actualizarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 117, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 224));
        jLabel3.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("MERCADERIA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Guardarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Guardarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Guardarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Guardarbtn.setText("Guardar");
        Guardarbtn.setBorder(null);
        Guardarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardarbtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Guardarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 117, 35));

        Cantidadtxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Cantidadtxt.setForeground(new java.awt.Color(102, 102, 102));
        Cantidadtxt.setText("Cantidad");
        Cantidadtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cantidadtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Cantidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadtxtActionPerformed(evt);
            }
        });
        Cantidadtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CantidadtxtKeyPressed(evt);
            }
        });
        jPanel2.add(Cantidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 250, 43));

        Productojcmb.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        Productojcmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Productojcmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 253, 42));

        jLabel11.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Fecha");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        Totaltxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Totaltxt.setForeground(new java.awt.Color(102, 102, 102));
        Totaltxt.setText("Total");
        Totaltxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Totaltxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotaltxtActionPerformed(evt);
            }
        });
        Totaltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TotaltxtKeyPressed(evt);
            }
        });
        jPanel2.add(Totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 140, 43));
        jPanel2.add(FechaCalendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, 125));

        Stocktxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Stocktxt.setForeground(new java.awt.Color(102, 102, 102));
        Stocktxt.setText("Stock");
        Stocktxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Stocktxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Stocktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StocktxtActionPerformed(evt);
            }
        });
        Stocktxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StocktxtKeyPressed(evt);
            }
        });
        jPanel2.add(Stocktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 140, 43));

        jLabel10.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Buscar código de Lote");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        AgregaMercaderiabtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        AgregaMercaderiabtn.setForeground(new java.awt.Color(102, 102, 102));
        AgregaMercaderiabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas.png"))); // NOI18N
        AgregaMercaderiabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(AgregaMercaderiabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 40, -1));

        jLabel8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Tipo de Pieza");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        Productojcmb1.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        Productojcmb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Productojcmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 253, 42));

        jButton4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButton4.setToolTipText("");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 40, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotaltxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotaltxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            total = Integer.parseInt(Totaltxt.getText());

        }
    }//GEN-LAST:event_TotaltxtKeyPressed

    private void TotaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotaltxtActionPerformed

    private void CantidadtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadtxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cantidad = Integer.parseInt(Cantidadtxt.getText());

        }
    }//GEN-LAST:event_CantidadtxtKeyPressed

    private void CantidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadtxtActionPerformed
    List Proveedores = new ArrayList();

    static void obtener_proveedor(ArrayList<Integer> id, ArrayList<String> Proveedor) {
        int ID = 0;
        String proveedor = "";
        id.get(ID);
        Proveedor.get(Integer.parseInt(proveedor));
    }

    private void GuardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarbtnActionPerformed
        java.util.Date date = new java.util.Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        producto = (String) Productojcmb.getSelectedItem();
        cantidad = Integer.parseInt(Cantidadtxt.getText());
        total = Float.parseFloat(Totaltxt.getText());
        stock = Integer.parseInt(Stocktxt.getText());
        loteAverio = String.valueOf(Productojcmb1.getSelectedItem());
        fecha = f.format(FechaCalendar2.getDate());

        System.out.println(producto);
        System.out.println(cantidad);
        System.out.println(total);
        System.out.println(loteAverio);
        System.out.println(fecha);

        mercaderiasql.InsertarMercaderia(producto, cantidad, fecha, total, loteAverio, stock);
        //String numCadena = String.valueOf(numEntero);

        //  loteAverio = (String) Productojcmb1.getSelectedItem();
        loteAverio = lote.getLoteAverio();
        pruebasql.LotePollo(loteAverio);
        // System.out.println(pruebasql.getLoteAverio2());
        //System.out.println(pruebasql.getUnidadExistente2());
        int existenciasActualizadas = pruebasql.getUnidadExistente2() - Integer.parseInt(Stocktxt.getText());
        //  System.out.println(existenciasActualizadas);
        SQLupdateMateriaPrima.ActualizarExistenciasDeMateriaPrima(existenciasActualizadas, pruebasql.getLoteAverio2());

        Stocktxt.setText("Stock");
        Cantidadtxt.setText("Cantidad");
        Totaltxt.setText("Total");

    }//GEN-LAST:event_GuardarbtnActionPerformed

    private void ActualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarbtnActionPerformed

        EliminarMercaderia mp = new EliminarMercaderia();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_ActualizarbtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Menu3 menux = new Menu3();
        menux.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    private void Pintar(Color colorbotones, String imagen, Color colortexto, Color colorlabel, Color colorbase, Color colorfondo) {
        panel.setPanelBase(jPanel2);
        panel.setColorBase(colorbase);
        panel.getPanelBase();
        panel.setPanelFondo(jPanel1);
        panel.setColorFondo(colorfondo);
        panel.getPanelFondo();
        boton.setBoton(Actualizarbtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(AgregaMercaderiabtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();
        boton.setBoton(Guardarbtn);
        boton.setColorBoton(colorbotones);
        boton.getBoton();

        text.setText(Stocktxt);
        text.setColorTexto(colortexto);
        text.getText();
        text.setText(Cantidadtxt);
        text.setColorTexto(colortexto);
        text.getText();
        text.setText(Totaltxt);
        text.setColorTexto(colortexto);
        text.getText();
        label.setLabel(jLabel3);
        label.setColorLabel(colorlabel);
        label.getLabel();

    }
    private void StocktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StocktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StocktxtActionPerformed

    private void StocktxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StocktxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_StocktxtKeyPressed
    boolean modoOscuro = false;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mercaderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mercaderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mercaderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mercaderia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mercaderia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizarbtn;
    private javax.swing.JButton AgregaMercaderiabtn;
    private javax.swing.JTextField Cantidadtxt;
    private com.toedter.calendar.JCalendar FechaCalendar2;
    private javax.swing.JButton Guardarbtn;
    private javax.swing.JComboBox<String> Productojcmb;
    private javax.swing.JComboBox<String> Productojcmb1;
    private javax.swing.JTextField Stocktxt;
    private javax.swing.JTextField Totaltxt;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
