/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Usuario;
import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import ClasesInterfaz.ComponenteRadioButon;
import ClasesSQL.MateriaPrimaSQL;
import ClasesSQL.PerdidaMateriaPrimaSQL;
import ClasesSQL.UpdateMateriaPrimaSQL;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import sun.security.util.Password;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author jenif
 */
public class PerdidaMateriaPrima extends javax.swing.JFrame {

    MateriaPrimaSQL SQLMateriaPrima = new MateriaPrimaSQL();
    String codigo = "", codigoperdida = "";
    int cantidad = 0;
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();
    ComponenteRadioButon radio = new ComponenteRadioButon();
    MateriaPrimaSQL SQLlamateriaprima = new MateriaPrimaSQL();
    Clases.MateriaPrima materiaprima = new Clases.MateriaPrima();
    ArrayList<Clases.MateriaPrima> listaMateriaPrima = SQLlamateriaprima.ConsultaMateraPrimaCodigo();
    Clases.PerdidaMateriaPrima perdidamateriaprima = new Clases.PerdidaMateriaPrima();
    Clases.MovimientoLotePerdida movimientoperdida = new Clases.MovimientoLotePerdida();
    PerdidaMateriaPrimaSQL SQLPerdidaMateriaPrima = new PerdidaMateriaPrimaSQL();
    UpdateMateriaPrimaSQL SQLupdateMateriaPrima = new UpdateMateriaPrimaSQL();
    Clases.Usuario usuario = new Clases.Usuario();

    /*crud thecrud = new crud();
    Connection con = (Connection) ConexionBD.GetConnection();*/
    /**
     * Creates new form Menu
     */
    public PerdidaMateriaPrima() {

        //  this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
        for (Clases.MateriaPrima materia : listaMateriaPrima) {
            CodigoAveriocmb.addItem(materia.getLoteAverio());
        }
    }

    public PerdidaMateriaPrima(Usuario usuario) {

        //   this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
        for (Clases.MateriaPrima materia : listaMateriaPrima) {
            CodigoAveriocmb.addItem(materia.getLoteAverio());
        }
        this.usuario = usuario;
    }

    public void transparenciButton() {

        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        String texto2 = "Regresar a Menú Principal";
        jButton4.setToolTipText(texto2);
        String texto3 = "Generar Código Automáticamente";
        GeneradorDeCodigo.setToolTipText(texto3);
        String texto4 = "Guardar Perdida";
        Guardarbtn.setToolTipText(texto4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perdidas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Actualizarbtn = new javax.swing.JButton();
        Guardarbtn = new javax.swing.JButton();
        CodigoPerdidatxt = new javax.swing.JTextField();
        Eliminarbtn = new javax.swing.JButton();
        Enfermorbtn = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        FechaCalendar2 = new com.toedter.calendar.JCalendar();
        jLabel3 = new javax.swing.JLabel();
        Observacionbtn = new javax.swing.JRadioButton();
        Muertosrbtn = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        CodigoAveriocmb = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Cantidadtxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        GeneradorDeCodigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1109, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 125, 125));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(920, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(920, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Actualizarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Actualizarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Actualizarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Actualizarbtn.setText("Actualizar");
        Actualizarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Actualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Actualizarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 144, 34));

        Guardarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Guardarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Guardarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Guardarbtn.setText("Guardar");
        Guardarbtn.setBorder(null);
        Guardarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Guardarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 144, 34));

        CodigoPerdidatxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        CodigoPerdidatxt.setForeground(new java.awt.Color(102, 102, 102));
        CodigoPerdidatxt.setText("Código de la perdida");
        CodigoPerdidatxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CodigoPerdidatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoPerdidatxtActionPerformed(evt);
            }
        });
        CodigoPerdidatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CodigoPerdidatxtKeyPressed(evt);
            }
        });
        jPanel2.add(CodigoPerdidatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, 43));

        Eliminarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Eliminarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Eliminarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Eliminarbtn.setText("Eliminar");
        Eliminarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Eliminarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 144, 34));

        Enfermorbtn.setBackground(new java.awt.Color(255, 255, 255));
        Perdidas.add(Enfermorbtn);
        Enfermorbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Enfermorbtn.setForeground(new java.awt.Color(51, 51, 51));
        Enfermorbtn.setText("Enfermedad");
        Enfermorbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enfermorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnfermorbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Enfermorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Fecha de la perdida");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));
        jPanel2.add(FechaCalendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 400, 150));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("PERDIDA DE LA MATERIA PRIMA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        Observacionbtn.setBackground(new java.awt.Color(255, 255, 255));
        Perdidas.add(Observacionbtn);
        Observacionbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Observacionbtn.setForeground(new java.awt.Color(51, 51, 51));
        Observacionbtn.setText("En observación");
        Observacionbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Observacionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObservacionbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Observacionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        Muertosrbtn.setBackground(new java.awt.Color(255, 255, 255));
        Perdidas.add(Muertosrbtn);
        Muertosrbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Muertosrbtn.setForeground(new java.awt.Color(51, 51, 51));
        Muertosrbtn.setText("Fallecimiento");
        Muertosrbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Muertosrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuertosrbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Muertosrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Tipo de Pérdida");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        CodigoAveriocmb.setEditable(true);
        CodigoAveriocmb.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        CodigoAveriocmb.setForeground(new java.awt.Color(102, 102, 102));
        CodigoAveriocmb.setToolTipText("");
        CodigoAveriocmb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(CodigoAveriocmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 250, 50));

        jLabel16.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Código de producto");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        Cantidadtxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Cantidadtxt.setForeground(new java.awt.Color(102, 102, 102));
        Cantidadtxt.setText("Unidades afectadas");
        Cantidadtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cantidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadtxtActionPerformed(evt);
            }
        });
        Cantidadtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CantidadtxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadtxtKeyTyped(evt);
            }
        });
        jPanel2.add(Cantidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 253, 43));

        jButton4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 60, -1));

        GeneradorDeCodigo.setBackground(new java.awt.Color(211, 84, 0));
        GeneradorDeCodigo.setFont(new java.awt.Font("Candara Light", 1, 16)); // NOI18N
        GeneradorDeCodigo.setForeground(new java.awt.Color(255, 255, 255));
        GeneradorDeCodigo.setText("Generar código");
        GeneradorDeCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GeneradorDeCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneradorDeCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(GeneradorDeCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Menu3 menux = new Menu3();
        menux.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CodigoPerdidatxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoPerdidatxtKeyPressed
        // TODO add your handling code here:
        /* if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cantidad = Integer.parseInt(CodigoPerdidatxt.getText());

        }*/
    }//GEN-LAST:event_CodigoPerdidatxtKeyPressed

    private void CodigoPerdidatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoPerdidatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoPerdidatxtActionPerformed
    /* List Proveedores = new ArrayList();

    static void obtener_proveedor(ArrayList<Integer> id, ArrayList<String> Proveedor) {
        int ID = 0;
        String proveedor = "";
        id.get(ID);
        Proveedor.get(Integer.parseInt(proveedor));
    }*/
    private void GuardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarbtnActionPerformed
        codigoperdida = CodigoPerdidatxt.getText();
        codigo = (String) CodigoAveriocmb.getSelectedItem();
        System.out.println(codigo);
        perdidamateriaprima.setIdPerdidaMateriaPrima(codigoperdida);
        perdidamateriaprima.setMuerto(Muertosrbtn.isSelected());
        perdidamateriaprima.setEnfermo(Enfermorbtn.isSelected());
        perdidamateriaprima.setEnObservacion(Observacionbtn.isSelected());
        perdidamateriaprima.setUnidadesAfectadas(Integer.parseInt(Cantidadtxt.getText()));
        perdidamateriaprima.setFecha(formato.format(FechaCalendar2.getDate()));
        materiaprima.setLoteAverio(codigo);
        movimientoperdida.setCodigolotePollo(materiaprima);
        movimientoperdida.setCodigoperdidaMateriaPrima(perdidamateriaprima);
        movimientoperdida.setPerdidaMateriaPrima(true);
        for (Clases.MateriaPrima materia : listaMateriaPrima) {
            CodigoAveriocmb.addItem(materia.getLoteAverio());
            if (materia.getLoteAverio().equals(materiaprima.getLoteAverio())) {
                if (materia.getUnidadExistente() >= Integer.parseInt(Cantidadtxt.getText())) {
                    SQLPerdidaMateriaPrima.InsertarPerdidaMateriaPrima(perdidamateriaprima);
                    SQLPerdidaMateriaPrima.InsertarPerdidaMovimientoLote(movimientoperdida);
                    int existenciasActualizadas = materia.getUnidadExistente() - Integer.parseInt(Cantidadtxt.getText());
                    SQLupdateMateriaPrima.ActualizarExistenciasDeMateriaPrima(existenciasActualizadas, codigo);
                } else {
                    JOptionPane.showMessageDialog(null, "No se pueden perder lo que no se tiene. Verifique la cantidad");
                }
            }
        }

        Cantidadtxt.setText("Unidades afectadas");
        CodigoPerdidatxt.setText("Código de la perdida");
        CodigoAveriocmb.setSelectedIndex(0);
        Muertosrbtn.setSelected(false);
        FechaCalendar2.setDate(null);

    }//GEN-LAST:event_GuardarbtnActionPerformed

    private void ActualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarbtnActionPerformed

    }//GEN-LAST:event_ActualizarbtnActionPerformed

    private void EnfermorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnfermorbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnfermorbtnActionPerformed

    private void ObservacionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObservacionbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObservacionbtnActionPerformed

    private void MuertosrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuertosrbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuertosrbtnActionPerformed
    boolean modoOscuro = false;
    private void CantidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadtxtActionPerformed

    private void CantidadtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadtxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadtxtKeyPressed

    private void CantidadtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadtxtKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_CantidadtxtKeyTyped

    private void EliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarbtnActionPerformed

    }//GEN-LAST:event_EliminarbtnActionPerformed

    private void GeneradorDeCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneradorDeCodigoActionPerformed
        // TODO add your handling code here:
        SQLMateriaPrima.getFiveDigitsNumber();
        // System.out.println(SQLMateriaPrima.getFiveDigitsNumber());
        String aux = String.valueOf(SQLMateriaPrima.getFiveDigitsNumber());
        CodigoPerdidatxt.setText(aux);
    }//GEN-LAST:event_GeneradorDeCodigoActionPerformed
    private void Pintar(Color colorbotones, String imagen, Color colortexto, Color colorlabel, Color colorbase, Color colorfondo) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerdidaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerdidaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerdidaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerdidaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerdidaMateriaPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizarbtn;
    private javax.swing.JTextField Cantidadtxt;
    private javax.swing.JComboBox<String> CodigoAveriocmb;
    private javax.swing.JTextField CodigoPerdidatxt;
    private javax.swing.JButton Eliminarbtn;
    private javax.swing.JRadioButton Enfermorbtn;
    private com.toedter.calendar.JCalendar FechaCalendar2;
    private javax.swing.JButton GeneradorDeCodigo;
    private javax.swing.JButton Guardarbtn;
    private javax.swing.JRadioButton Muertosrbtn;
    private javax.swing.JRadioButton Observacionbtn;
    private javax.swing.ButtonGroup Perdidas;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
