/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import ClasesSQL.LibretaClienteSQL;
import ClasesSQL.ProveedorSQL;
import static Interfaz.ProveedorVista.nombreReferencia;
import Usuario.Compresor;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author jenif
 */
public class Proveedor extends javax.swing.JFrame {

    String nombre = "", telefono = "", direccion = "", empresa = "";
    ProveedorSQL proveedorSQL = new ProveedorSQL();
    // Clases.MateriaPrima materiaprima = new Clases.MateriaPrima();
    Clases.Proveedor prov = new Clases.Proveedor();
    int IdProveedor = 0;
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();

    /**
     * Creates new form Menu
     */
    public Proveedor() {

        //  this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciButton();
        String texto="Regresar a Menu";
        jButton3.setToolTipText(texto);
    }

    public void transparenciButton() {
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        Buscartxt.setOpaque(false);
        Buscartxt.setContentAreaFilled(false);
        Buscartxt.setBorderPainted(false);
         String texto2 = "Regresar a Menú Principal";
        jButton3.setToolTipText(texto2);
        String texto3 = "Buscar Proveedor";
        Buscartxt.setToolTipText(texto3);
        String texto4 = "Guardar Proveedor";
        CrearCuentabtn.setToolTipText(texto4);
        String texto6 = "Actualizar Proveedor";
        ActualizarCuentabtn.setToolTipText(texto6);
        String texto5 = "Haga click para acceder a Eliminación de Proveedor";
        EliminarCuentabtn.setToolTipText(texto5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CrearCuentabtn = new javax.swing.JButton();
        TelefonoProveedortxt = new javax.swing.JTextField();
        EmpresaProveedortxt = new javax.swing.JTextField();
        EliminarCuentabtn = new javax.swing.JButton();
        ActualizarCuentabtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        NombreProveedortxt1 = new javax.swing.JTextField();
        direcciontxt = new javax.swing.JTextField();
        Buscartxt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 125, 125));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        CrearCuentabtn.setBackground(new java.awt.Color(211, 84, 0));
        CrearCuentabtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        CrearCuentabtn.setForeground(new java.awt.Color(255, 255, 255));
        CrearCuentabtn.setText("Guardar");
        CrearCuentabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearCuentabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentabtnActionPerformed(evt);
            }
        });

        TelefonoProveedortxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        TelefonoProveedortxt.setForeground(new java.awt.Color(102, 102, 102));
        TelefonoProveedortxt.setText("Teléfono");
        TelefonoProveedortxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TelefonoProveedortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoProveedortxtActionPerformed(evt);
            }
        });
        TelefonoProveedortxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelefonoProveedortxtKeyPressed(evt);
            }
        });

        EmpresaProveedortxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        EmpresaProveedortxt.setForeground(new java.awt.Color(102, 102, 102));
        EmpresaProveedortxt.setText("Empresa");
        EmpresaProveedortxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EmpresaProveedortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpresaProveedortxtActionPerformed(evt);
            }
        });
        EmpresaProveedortxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpresaProveedortxtKeyPressed(evt);
            }
        });

        EliminarCuentabtn.setBackground(new java.awt.Color(211, 84, 0));
        EliminarCuentabtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        EliminarCuentabtn.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCuentabtn.setText("Eliminar");
        EliminarCuentabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarCuentabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCuentabtnActionPerformed(evt);
            }
        });

        ActualizarCuentabtn.setBackground(new java.awt.Color(211, 84, 0));
        ActualizarCuentabtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        ActualizarCuentabtn.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarCuentabtn.setText("Actualizar");
        ActualizarCuentabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActualizarCuentabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarCuentabtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("PROVEEDOR");

        NombreProveedortxt1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NombreProveedortxt1.setForeground(new java.awt.Color(102, 102, 102));
        NombreProveedortxt1.setText("Nombre Completo");
        NombreProveedortxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreProveedortxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProveedortxt1ActionPerformed(evt);
            }
        });
        NombreProveedortxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreProveedortxt1KeyPressed(evt);
            }
        });

        direcciontxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        direcciontxt.setForeground(new java.awt.Color(102, 102, 102));
        direcciontxt.setText("Dirección");
        direcciontxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        direcciontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direcciontxtActionPerformed(evt);
            }
        });
        direcciontxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                direcciontxtKeyPressed(evt);
            }
        });

        Buscartxt.setBackground(new java.awt.Color(102, 102, 102));
        Buscartxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Buscartxt.setForeground(new java.awt.Color(102, 102, 102));
        Buscartxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa (1).png"))); // NOI18N
        Buscartxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscartxt.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aprovechar.png"))); // NOI18N
        Buscartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscartxtActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NombreProveedortxt1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelefonoProveedortxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmpresaProveedortxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ActualizarCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CrearCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(direcciontxt))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(Buscartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(NombreProveedortxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TelefonoProveedortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmpresaProveedortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualizarCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelefonoProveedortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoProveedortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoProveedortxtActionPerformed

    private void TelefonoProveedortxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoProveedortxtKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            telefono = TelefonoProveedortxt.getText();
            direcciontxt.setText("");
            direcciontxt.requestFocus();
        }
    }//GEN-LAST:event_TelefonoProveedortxtKeyPressed

    private void CrearCuentabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentabtnActionPerformed
        nombre = NombreProveedortxt1.getText();
        telefono = TelefonoProveedortxt.getText();
        direccion = direcciontxt.getText();
        empresa = EmpresaProveedortxt.getText();
        System.out.println(nombre);
        System.out.println(telefono);
        System.out.println(direccion);
        System.out.println(empresa);
        proveedorSQL.InsertarProveedor(nombre, direccion, telefono, empresa);
        NombreProveedortxt1.setText("Nombre Completo");
        TelefonoProveedortxt.setText("Teléfono");
        direcciontxt.setText("Direción");
        EmpresaProveedortxt.setText("Empresa");
    }//GEN-LAST:event_CrearCuentabtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu3 menu = new Menu3();
        menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void EmpresaProveedortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpresaProveedortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpresaProveedortxtActionPerformed

    private void EmpresaProveedortxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpresaProveedortxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            empresa = EmpresaProveedortxt.getText();

        }
    }//GEN-LAST:event_EmpresaProveedortxtKeyPressed

    private void EliminarCuentabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCuentabtnActionPerformed
        // TODO add your handling code here:
        /*    proveedorSQL.DeleteProveedor(IdProveedor);
        NombreProveedortxt1.setText(null);
        TelefonoProveedortxt.setText(null);
        direcciontxt.setText(null);
        EmpresaProveedortxt.setText(null);*/
        ProveedorVista inventario = new ProveedorVista();
        inventario.setVisible(true);
        dispose();
    }//GEN-LAST:event_EliminarCuentabtnActionPerformed

    private void ActualizarCuentabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarCuentabtnActionPerformed
        // TODO add your handling code here:
        nombre = NombreProveedortxt1.getText();
        telefono = TelefonoProveedortxt.getText();
        direccion = direcciontxt.getText();
        empresa = EmpresaProveedortxt.getText();
        System.out.println(nombre);
        System.out.println(telefono);
        System.out.println(direccion);
        System.out.println(empresa);
        proveedorSQL.ActualizarProveedor(nombre, direccion, telefono, empresa);
    }//GEN-LAST:event_ActualizarCuentabtnActionPerformed

    private void NombreProveedortxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProveedortxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProveedortxt1ActionPerformed

    private void NombreProveedortxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreProveedortxt1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProveedortxt1KeyPressed

    boolean modoOscuro = false;

    private void Pintar(Color colorbotones, String imagen, Color colortexto, Color colorlabel, Color colorbase, Color colorfondo) {
        

    }

    private void direcciontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direcciontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direcciontxtActionPerformed

    private void direcciontxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direcciontxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_direcciontxtKeyPressed

    private void BuscartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscartxtActionPerformed
        // TODO add your handling code here:
        String nombreProveedor = JOptionPane.showInputDialog("Ingrese el nombre del Proveedor, por favor");
        IdProveedor = proveedorSQL.BuscarProveedorPorNombre(NombreProveedortxt1, TelefonoProveedortxt, direcciontxt, EmpresaProveedortxt, nombreProveedor);
        //   System.out.println("idProveedor" + IdProveedor);

    }//GEN-LAST:event_BuscartxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarCuentabtn;
    private javax.swing.JButton Buscartxt;
    private javax.swing.JButton CrearCuentabtn;
    private javax.swing.JButton EliminarCuentabtn;
    private javax.swing.JTextField EmpresaProveedortxt;
    private javax.swing.JTextField NombreProveedortxt1;
    private javax.swing.JTextField TelefonoProveedortxt;
    private javax.swing.JTextField direcciontxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
