/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Cuentas;
import Clases.Lista;
import Clases.Venta;
import ClasesInterfaz.ComponenteBoton;
import ClasesInterfaz.ComponenteBotonIcon;
import ClasesInterfaz.ComponenteLabelText;
import ClasesInterfaz.ComponentePanel;
import ClasesSQL.MercaderiaSQL;
import ClasesSQL.PersonalSQL;
import Usuario.Compresor;
import ClasesSQL.PruebaSQL;
import ClasesSQL.VentaSQL;
import Conexion.ConexionBD;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import sun.security.util.Password;

public class RegistroCuentas extends javax.swing.JFrame {

    Connection connection = ConexionBD.getConnection();
    Compresor compresor = new Compresor();
    DefaultTableModel model;
    Scanner sc = new Scanner(System.in);
    ArrayList<Venta> listaOriginal = new ArrayList<Venta>();
    ArrayList<Cuentas> listaOriginal2 = new ArrayList<Cuentas>();
    java.util.Date date = new java.util.Date();
    SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
    PruebaSQL pruebasql = new PruebaSQL();
    PersonalSQL personalSQL = new PersonalSQL();
    MercaderiaSQL mercaderia2 = new MercaderiaSQL();
    VentaSQL ventasql = new VentaSQL();
    boolean aDomicilio, puntoDeVenta, modoOscuro, Debe, Haber;
    int cantidad = 0, cantidad2 = 0, cantidadProducto, ciclo, anio;
    float total = 0, total2, monto;
    int Anio;
    String Usuario = "", pass_concatenada = "", nombreproveedor = "", tipoproducto = "", producto = "", fecha, nombreProducto;
    String Cuenta = "", Aux = "", Concepto = "", Mes = "";
    char[] password;
    // Definimos el largo de la casilla para la contraseña
    JPasswordField passwordField = new JPasswordField(15);
    JTextField jtextField = new JTextField(15);
    ComponentePanel panel = new ComponentePanel();
    ComponenteLabelText text = new ComponenteLabelText();
    ComponenteLabelText label = new ComponenteLabelText();
    ComponenteBoton boton = new ComponenteBoton();
    ComponenteBotonIcon botonIcon = new ComponenteBotonIcon();

    public RegistroCuentas() {
        //  this.setUndecorated(true);
        initComponents();
        model = new DefaultTableModel();
        model.addColumn("Tipo");
        model.addColumn("Tipo");
        model.addColumn("Cuenta");
        model.addColumn("Cuenta");
        model.addColumn("Concepto");
        ProductoJcmbx1.addItem("Enero");
        ProductoJcmbx1.addItem("Febrero");
        ProductoJcmbx1.addItem("Marzo");
        ProductoJcmbx1.addItem("Abril");
        ProductoJcmbx1.addItem("Mayo");
        ProductoJcmbx1.addItem("Junio");
        ProductoJcmbx1.addItem("Julio");
        ProductoJcmbx1.addItem("Agosto");
        ProductoJcmbx1.addItem("Septiembre");
        ProductoJcmbx1.addItem("Octubre");
        ProductoJcmbx1.addItem("Noviembre");
        ProductoJcmbx1.addItem("Diciembre");
        ProductoJcmbx.addItem("Ventas");
        ProductoJcmbx.addItem("Gastos");
        ProductoJcmbx3.addItem("Caja");
        ProductoJcmbx3.addItem("Sueldos y Salarios");
        ProductoJcmbx2.addItem("2023");
        this.jTable1.setModel(model);
        this.setLocationRelativeTo(null);
        transparenciButton();
        //  mercaderia2.ConsultaDeMercaderia(ProductoJcmbx);
    }

    public void transparenciButton() {
        AgregarProductobtn.setOpaque(false);
        AgregarProductobtn.setContentAreaFilled(false);
        AgregarProductobtn.setBorderPainted(false);
        Verbtn.setOpaque(false);
        Verbtn.setContentAreaFilled(false);
        Verbtn.setBorderPainted(false);
        Verbtn1.setOpaque(false);
        Verbtn1.setContentAreaFilled(false);
        Verbtn1.setBorderPainted(false);
        regresarbtn.setOpaque(false);
        regresarbtn.setContentAreaFilled(false);
        regresarbtn.setBorderPainted(false);
        AgregarProductobtn1.setOpaque(false);
        AgregarProductobtn1.setContentAreaFilled(false);
        AgregarProductobtn1.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Guardarbtn = new javax.swing.JButton();
        ProductoJcmbx = new javax.swing.JComboBox<>();
        AgregarProductobtn = new javax.swing.JButton();
        Adomijbtn = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cantidadtxt = new javax.swing.JTextField();
        totaltxt = new javax.swing.JTextField();
        Verbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Verbtn1 = new javax.swing.JButton();
        regresarbtn = new javax.swing.JButton();
        ProductoJcmbx1 = new javax.swing.JComboBox<>();
        ProductoJcmbx2 = new javax.swing.JComboBox<>();
        ProductoJcmbx3 = new javax.swing.JComboBox<>();
        AgregarProductobtn1 = new javax.swing.JButton();
        Guardarbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(123, 125, 125));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("REGISTROS");

        Guardarbtn.setBackground(new java.awt.Color(211, 84, 0));
        Guardarbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Guardarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Guardarbtn.setText("Guardar");
        Guardarbtn.setBorder(null);
        Guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarbtnActionPerformed(evt);
            }
        });

        ProductoJcmbx.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        ProductoJcmbx.setForeground(new java.awt.Color(102, 102, 102));
        ProductoJcmbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta" }));
        ProductoJcmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoJcmbxActionPerformed(evt);
            }
        });

        AgregarProductobtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AgregarProductobtn.setText("+");
        AgregarProductobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductobtnActionPerformed(evt);
            }
        });

        Adomijbtn.setBackground(new java.awt.Color(255, 255, 255));
        Adomijbtn.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Adomijbtn.setForeground(new java.awt.Color(51, 51, 51));
        Adomijbtn.setText("Debe");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setText("Haber");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Adomicilio", "Punto De Venta", "Producto", "Cantidad", "Total", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        cantidadtxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        cantidadtxt.setForeground(new java.awt.Color(102, 102, 102));
        cantidadtxt.setText("Concepto");
        cantidadtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cantidadtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantidadtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadtxtActionPerformed(evt);
            }
        });
        cantidadtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadtxtKeyPressed(evt);
            }
        });

        totaltxt.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        totaltxt.setForeground(new java.awt.Color(102, 102, 102));
        totaltxt.setText("Monto");
        totaltxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totaltxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });
        totaltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totaltxtKeyPressed(evt);
            }
        });

        Verbtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Verbtn.setForeground(new java.awt.Color(102, 102, 102));
        Verbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojo (3).png"))); // NOI18N
        Verbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerbtnActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Verbtn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Verbtn1.setForeground(new java.awt.Color(102, 102, 102));
        Verbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprobado (1).png"))); // NOI18N
        Verbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verbtn1ActionPerformed(evt);
            }
        });

        regresarbtn.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        regresarbtn.setForeground(new java.awt.Color(102, 102, 102));
        regresarbtn.setText("Regresar");
        regresarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarbtnActionPerformed(evt);
            }
        });

        ProductoJcmbx1.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        ProductoJcmbx1.setForeground(new java.awt.Color(102, 102, 102));
        ProductoJcmbx1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes" }));
        ProductoJcmbx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoJcmbx1ActionPerformed(evt);
            }
        });

        ProductoJcmbx2.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        ProductoJcmbx2.setForeground(new java.awt.Color(102, 102, 102));
        ProductoJcmbx2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        ProductoJcmbx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoJcmbx2ActionPerformed(evt);
            }
        });

        ProductoJcmbx3.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        ProductoJcmbx3.setForeground(new java.awt.Color(102, 102, 102));
        ProductoJcmbx3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auxiliar" }));
        ProductoJcmbx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoJcmbx3ActionPerformed(evt);
            }
        });

        AgregarProductobtn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AgregarProductobtn1.setText("+");
        AgregarProductobtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductobtn1ActionPerformed(evt);
            }
        });

        Guardarbtn1.setBackground(new java.awt.Color(211, 84, 0));
        Guardarbtn1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        Guardarbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Guardarbtn1.setText("Ver");
        Guardarbtn1.setBorder(null);
        Guardarbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardarbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(ProductoJcmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(AgregarProductobtn))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(ProductoJcmbx3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(AgregarProductobtn1))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(Adomijbtn)
                                                .addGap(45, 45, 45)
                                                .addComponent(jRadioButton2))
                                            .addComponent(cantidadtxt)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(ProductoJcmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ProductoJcmbx2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(totaltxt))))
                                .addGap(0, 90, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Verbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Guardarbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Guardarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Verbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(regresarbtn)
                        .addGap(50, 50, 50))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(regresarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(308, 308, 308)
                                .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Verbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoJcmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoJcmbx2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoJcmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarProductobtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoJcmbx3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarProductobtn1))
                        .addGap(18, 18, 18)
                        .addComponent(cantidadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Adomijbtn)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Verbtn1)
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardarbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarbtnActionPerformed

        //Para obtener ID del Usuario
        //CONTRASEÑA
        JPanel panel = new JPanel();
        JLabel label2 = new JLabel("Usuario:");
        JLabel label = new JLabel("Contraseña:");
        // Agregamos los componentes al panel
        panel.add(label2);
        panel.add(jtextField);
        panel.add(label);
        panel.add(passwordField);

        // Definimos el texto de las opciones para aceptar o cancelar
        String[] options = new String[]{"Aceptar", "Cancelar"};
        // Agregamos el panel y las opciones al dialogo
        int option = JOptionPane.showOptionDialog(null, panel, "Ingreso de datos usuario",
                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[1]);

        //CONTRASEÑA
        if (option == 0) // pressing OK button
        {
            Usuario = jtextField.getText();
            System.out.println("Usuario: " + Usuario);
            password = passwordField.getPassword();

            for (int i = 0; i < password.length; i++) {
                pass_concatenada = pass_concatenada + password[i];
                System.out.println(password[i]);
            }

            pruebasql.BuscarUsuario(Usuario, pass_concatenada);
        } else {
            System.out.println("Ingreso de contraseña cancelada");

        }
        //personalSQL.InsertarCuenta(Mes, Debe, Haber, Anio, monto, Cuenta, Aux, Concepto);

        for (Clases.Venta lista2 : listaOriginal) {
            System.out.println("Adomicilio" + lista2.isAdomicilio());
            System.out.println("Punto de venta" + lista2.isPuntoVenta());
            System.out.println("Producto" + lista2.getProducto());
            System.out.println("Cantidad:" + lista2.getCantidad());
            System.out.println("Total:" + lista2.getTotal());
            System.out.println("Fecha:" + lista2.getFecha());
            System.out.println(pruebasql.getVal());
            ventasql.InsertarVenta(lista2.isAdomicilio(), lista2.isPuntoVenta(), lista2.getProducto(), lista2.getCantidad(), lista2.getTotal(), lista2.getFecha(), pruebasql.getVal());

        }
        for (Clases.Cuentas lista2 : listaOriginal2) {
            System.out.println("Mes" + lista2.getFecha());
            System.out.println("Debe" + lista2.isDebe());
            System.out.println("Haber" + lista2.isHaber());
            int anio2 = 2023;
            System.out.println("Año" + anio2);
            System.out.println("Monto" + lista2.getMonto());
            System.out.println("Cuenta" + lista2.getCuenta());
            System.out.println("Aux" + lista2.getAuxiliar());
            System.out.println("Concepto" + lista2.getConcepto());

//personalSQL.InsertarCuenta(Mes, Debe, Haber, Anio, monto, Cuenta, Aux, Concepto);
            personalSQL.InsertarCuenta(lista2.getFecha(), lista2.isDebe(), lista2.isHaber(), anio2, lista2.getMonto(), lista2.getCuenta(), lista2.getAuxiliar(), lista2.getConcepto());

        }

    }//GEN-LAST:event_GuardarbtnActionPerformed

    private void AgregarProductobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductobtnActionPerformed
        // TODO add your handling code here:
        producto = JOptionPane.showInputDialog("Ingrese Producto");
        ProductoJcmbx.addItem(producto);

    }//GEN-LAST:event_AgregarProductobtnActionPerformed
    private void Pintar(Color colorbotones, String imagen, Color colortexto, Color colorlabel, Color colorbase, Color colorfondo) {

    }

    private void cantidadtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadtxtActionPerformed

    private void cantidadtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadtxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cantidad = Integer.parseInt(cantidadtxt.getText());
            totaltxt.setText("");
            totaltxt.requestFocus();
        }
    }//GEN-LAST:event_cantidadtxtKeyPressed

    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtActionPerformed

    private void totaltxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totaltxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            total = Float.parseFloat(totaltxt.getText());
        }
    }//GEN-LAST:event_totaltxtKeyPressed

    private void VerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerbtnActionPerformed
        // TODO add your handling code here:

        mostrar();
        ProductoJcmbx1.setSelectedIndex(0);
        ProductoJcmbx2.setSelectedIndex(0);
        ProductoJcmbx3.setSelectedIndex(0);
        cantidadtxt.setText("Concepto");
        totaltxt.setText("Monto");
        Adomijbtn.setSelected(false);
        jRadioButton2.setSelected(false);

    }//GEN-LAST:event_VerbtnActionPerformed
    public void mostrar() {

        String matris[][] = new String[listaOriginal2.size()][7];
        for (int i = 0; i < listaOriginal2.size(); i++) {

            /*matris[i][0] = String.valueOf(listaOriginal.get(i).isAdomicilio());
            matris[i][1] = String.valueOf(listaOriginal.get(i).isPuntoVenta());
            matris[i][2] = listaOriginal.get(i).getProducto();
            matris[i][3] = String.valueOf(listaOriginal.get(i).getCantidad());
            matris[i][4] = String.valueOf(listaOriginal.get(i).getTotal());
            matris[i][5] = listaOriginal.get(i).getFecha();*/
            matris[i][0] = String.valueOf(listaOriginal2.get(i).isDebe());
            matris[i][1] = String.valueOf(listaOriginal2.get(i).isHaber());
            matris[i][2] = listaOriginal2.get(i).getCuenta();
            matris[i][3] = listaOriginal2.get(i).getAuxiliar();
            matris[i][4] = listaOriginal2.get(i).getConcepto();
            //   matris[i][3] = String.valueOf(listaOriginal2.get(i).getCantidad());
            matris[i][5] = String.valueOf(listaOriginal2.get(i).getMonto());
            matris[i][6] = listaOriginal2.get(i).getFecha();

        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                matris,
                new String[]{
                    "Debe", "Haber", "Cuenta", "Aux", "Concepto", "Monto", "Fecha"
                }
        ));

    }
    private void ProductoJcmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoJcmbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoJcmbxActionPerformed

    private void Verbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verbtn1ActionPerformed
        // TODO add your handling code here:
        if (Adomijbtn.isSelected()) {
            Debe = true;
        }
        if (jRadioButton2.isSelected()) {
            Haber = true;
        }

        Mes = (String) ProductoJcmbx1.getSelectedItem();
        Cuenta = (String) ProductoJcmbx.getSelectedItem();
        Aux = (String) ProductoJcmbx3.getSelectedItem();
        Concepto = cantidadtxt.getText();
        Anio = Integer.parseInt((String) ProductoJcmbx2.getSelectedItem());
        monto = Float.parseFloat(totaltxt.getText());
        System.out.println(Mes);
        System.out.println(Cuenta);
        System.out.println(Aux);
        System.out.println(Concepto);
        System.out.println(Anio);
        System.out.println(monto);
        // fecha = f.format(FechaCalendar.getDate());
        //boolean Debe, boolean Haber, String Concepto, String Cuenta, String Auxiliar, float monto, String fecha
        Cuentas cuentas = new Cuentas(Haber, Debe, Concepto, Cuenta, Aux, monto, Mes);
        //  Venta venta = new Venta(aDomicilio, puntoDeVenta, tipoproducto, cantidad, total, fecha);
        listaOriginal2.add(cuentas);
        ProductoJcmbx1.setSelectedIndex(0);
        ProductoJcmbx2.setSelectedIndex(0);
        ProductoJcmbx3.setSelectedIndex(0);
        cantidadtxt.setText("Concepto");
        totaltxt.setText("Monto");
        Adomijbtn.setSelected(false);
        jRadioButton2.setSelected(false);


    }//GEN-LAST:event_Verbtn1ActionPerformed

    private void regresarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarbtnActionPerformed
        // TODO add your handling code here:
        MenuCuentas menux = new MenuCuentas();
        menux.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarbtnActionPerformed

    private void ProductoJcmbx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoJcmbx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoJcmbx1ActionPerformed

    private void ProductoJcmbx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoJcmbx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoJcmbx2ActionPerformed

    private void ProductoJcmbx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoJcmbx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoJcmbx3ActionPerformed

    private void AgregarProductobtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductobtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarProductobtn1ActionPerformed

    private void Guardarbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardarbtn1ActionPerformed
        // TODO add your handling code here:
        VerCuentas menux = new VerCuentas();
        menux.setVisible(true);
        dispose();
    }//GEN-LAST:event_Guardarbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Adomijbtn;
    private javax.swing.JButton AgregarProductobtn;
    private javax.swing.JButton AgregarProductobtn1;
    private javax.swing.JButton Guardarbtn;
    private javax.swing.JButton Guardarbtn1;
    private javax.swing.JComboBox<String> ProductoJcmbx;
    private javax.swing.JComboBox<String> ProductoJcmbx1;
    private javax.swing.JComboBox<String> ProductoJcmbx2;
    private javax.swing.JComboBox<String> ProductoJcmbx3;
    private javax.swing.JButton Verbtn;
    private javax.swing.JButton Verbtn1;
    private javax.swing.JTextField cantidadtxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton regresarbtn;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
